# """
# Autonomous BirdCLEF Research Agent (Slot Mode)
# ===============================================

# Architecture:
#   - Fixed harness: loads data, builds mel features, trains, evaluates, writes submission
#   - LLM slot:      writes only build_model() + get_training_config() (+ optional build_features())
#   - Agent loop:    run -> evaluate -> feed results back -> LLM proposes improvement -> repeat
#   - Final run:     retrain best architecture on ALL data, save model + submission + Kaggle notebook
# """

# from __future__ import annotations

# import json
# import re
# import ast
# import time
# from pathlib import Path
# from datetime import datetime

# if __package__:
#     from .code_executor import CodeExecutor
#     from .evaluator import Evaluator
#     from .llm_client import LLMClient
# else:
#     from code_executor import CodeExecutor
#     from evaluator import Evaluator
#     from llm_client import LLMClient


# def load_config(path: Path) -> dict:
#     with path.open("r", encoding="utf-8") as f:
#         return json.load(f)


# # ---------------------------------------------------------------------------
# # Fixed harness prefix (shared by iteration runs and final run)
# # ---------------------------------------------------------------------------

# HARNESS_PREFIX = '''
# """Auto-generated by agent: fixed harness + LLM slots."""
# from __future__ import annotations
# import os, sys, json
# from pathlib import Path
# import librosa, numpy as np, tensorflow as tf, matplotlib.pyplot as plt

# _PROJECT_ROOT = str(Path(__file__).resolve().parents[1])
# if _PROJECT_ROOT not in sys.path:
#     sys.path.insert(0, _PROJECT_ROOT)
# os.chdir(_PROJECT_ROOT)
# os.environ.setdefault("BIRDCLEF_DATA_DIR", str(Path(_PROJECT_ROOT) / "data"))

# from src.data_io import (
#     load_core_tables, resolve_birdclef_paths,
#     species_columns_from_sample_submission, validate_required_files,
# )

# def _default_load_mel(audio_path, sample_rate, clip_seconds, n_mels, n_frames):
#     target_len = int(sample_rate * clip_seconds)
#     wav, _ = librosa.load(audio_path, sr=sample_rate, mono=True, duration=clip_seconds)
#     if len(wav) < target_len:
#         wav = np.pad(wav, (0, target_len - len(wav)))
#     else:
#         wav = wav[:target_len]
#     mel = librosa.feature.melspectrogram(
#         y=wav, sr=sample_rate, n_mels=n_mels, n_fft=1024, hop_length=512, power=2.0,
#     )
#     mel_db = librosa.power_to_db(mel, ref=np.max)
#     mel_resized = tf.image.resize(mel_db[..., np.newaxis], (n_mels, n_frames)).numpy()
#     return mel_resized.astype(np.float32)
# '''.lstrip()


# def _make_harness_suffix(*, is_final: bool = False, model_save_path: str = "") -> str:
#     if is_final:
#         max_line = '    max_samples = None  # FINAL RUN: use ALL data'
#         save_block = (
#             f'\n    _mp = Path("{model_save_path}")\n'
#             '    _mp.parent.mkdir(parents=True, exist_ok=True)\n'
#             '    model.save(_mp)\n'
#             '    print(f"MODEL_SAVED: {_mp}")\n'
#         )
#     else:
#         max_line = '    max_samples = cfg.get("max_samples", 500)'
#         save_block = ''

#     return f'''

# def main():
#     global model, X_train, y_train
#     tf.keras.utils.set_random_seed(42)
#     cfg = get_training_config()
# {max_line}
#     sample_rate   = cfg.get("sample_rate", 32000)
#     clip_seconds  = cfg.get("clip_seconds", 5.0)
#     n_mels        = cfg.get("n_mels", 64)
#     n_frames      = cfg.get("n_frames", 128)
#     epochs        = cfg.get("epochs", 5)
#     batch_size    = cfg.get("batch_size", 32)
#     learning_rate = cfg.get("learning_rate", 1e-3)

#     paths = resolve_birdclef_paths()
#     missing = validate_required_files(paths)
#     if missing:
#         raise FileNotFoundError(f"Missing: {{missing}}")
#     tables = load_core_tables(paths)
#     train_df = tables["train"]
#     sample_sub = tables["sample_submission"]
#     species_cols = species_columns_from_sample_submission(sample_sub)
#     num_species = len(species_cols)
#     sp2i = {{s: i for i, s in enumerate(species_cols)}}
#     lcol = "primary_label" if "primary_label" in train_df.columns else "species_code"
#     fcol = "filename" if "filename" in train_df.columns else "filepath"

#     mel_fn = build_features if "build_features" in dir() and callable(build_features) else _default_load_mel

#     X_items, y_items = [], []
#     total = len(train_df)
#     for i, row in enumerate(train_df.itertuples(index=False)):
#         label = getattr(row, lcol)
#         rel = getattr(row, fcol)
#         if label not in sp2i:
#             continue
#         ap = paths.train_audio_dir / str(rel)
#         if not ap.exists():
#             continue
#         try:
#             mel = mel_fn(ap, sample_rate, clip_seconds, n_mels, n_frames)
#         except Exception:
#             continue
#         yv = np.zeros(num_species, dtype=np.float32)
#         yv[sp2i[label]] = 1.0
#         X_items.append(mel)
#         y_items.append(yv)
#         if max_samples and len(X_items) >= max_samples:
#             break
#         if len(X_items) % 500 == 0:
#             print(f"  Loaded {{len(X_items)}} samples (row {{i+1}}/{{total}})...")

#     if not X_items:
#         raise RuntimeError("No samples loaded.")
#     X_train = np.stack(X_items, dtype=np.float32)
#     y_train = np.stack(y_items, dtype=np.float32)
#     print(f"DATA: X_train={{X_train.shape}}, y_train={{y_train.shape}}")

#     model = build_model(X_train.shape[1:], num_species)
#     model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate), loss="binary_crossentropy")
#     model.summary()
#     history = model.fit(X_train, y_train, epochs=epochs, batch_size=min(batch_size, len(X_train)), verbose=1)
#     print(f"TRAIN_LOSS: {{history.history['loss'][-1]:.6f}}")
# {save_block}
#     y_pred = model.predict(X_train, verbose=0).astype(np.float32)
#     mean_pred = y_pred.mean(axis=0)
#     sub_df = sample_sub.copy()
#     for i, col in enumerate(species_cols):
#         sub_df[col] = float(mean_pred[i])
#     sub_path = Path("submission/submission_generated.csv")
#     sub_path.parent.mkdir(parents=True, exist_ok=True)
#     sub_df.to_csv(sub_path, index=False)
#     print(f"SUBMISSION: {{sub_path}}")

# if __name__ == "__main__":
#     main()
# '''


# # ---------------------------------------------------------------------------
# # Default slot code
# # ---------------------------------------------------------------------------

# DEFAULT_SLOT_CODE = '''def get_training_config():
#     return {
#         "max_samples": 500,
#         "sample_rate": 32000,
#         "clip_seconds": 5.0,
#         "n_mels": 64,
#         "n_frames": 128,
#         "epochs": 5,
#         "batch_size": 32,
#         "learning_rate": 1e-3,
#     }


# def build_model(input_shape, num_classes):
#     import tensorflow as tf
#     model = tf.keras.Sequential([
#         tf.keras.layers.Input(shape=input_shape),
#         tf.keras.layers.Conv2D(16, (3, 3), activation="relu", padding="same"),
#         tf.keras.layers.MaxPooling2D((2, 2)),
#         tf.keras.layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
#         tf.keras.layers.MaxPooling2D((2, 2)),
#         tf.keras.layers.Conv2D(64, (3, 3), activation="relu", padding="same"),
#         tf.keras.layers.MaxPooling2D((2, 2)),
#         tf.keras.layers.GlobalAveragePooling2D(),
#         tf.keras.layers.Dropout(0.3),
#         tf.keras.layers.Dense(num_classes, activation="sigmoid"),
#     ])
#     model.compile(optimizer="adam", loss="binary_crossentropy")
#     return model
# '''


# # ---------------------------------------------------------------------------
# # Prompts
# # ---------------------------------------------------------------------------

# SYSTEM_PROMPT = (
#     "You are an ML research assistant. You write Python functions to define "
#     "neural network architectures for bird species audio classification.\n\n"
#     "RULES:\n"
#     "- Return ONLY a ```python``` code block, nothing else\n"
#     "- Define exactly: get_training_config() and build_model(input_shape, num_classes)\n"
#     "- Optionally define: build_features(audio_path, sample_rate, clip_seconds, n_mels, n_frames)\n"
#     "- Do NOT define main(), do NOT load data, do NOT write submission logic\n"
#     "- build_model must return a COMPILED Keras model\n"
#     "- Last layer must be Dense(num_classes, activation='sigmoid')\n"
#     "- Loss must be 'binary_crossentropy'\n"
#     "- input_shape is (n_mels, n_frames, 1) — a mel spectrogram image\n"
#     "- num_classes is 234 (one per bird species)\n"
# )

# SEED_PROMPT = (
#     "Write get_training_config() and build_model() for BirdCLEF 2026.\n\n"
#     "Task: multi-label bird species classification from mel spectrograms.\n"
#     "Input: mel spectrogram of shape (n_mels, n_frames, 1), default (64, 128, 1).\n"
#     "Output: 234 species probabilities (sigmoid).\n"
#     "Loss: binary_crossentropy.\n\n"
#     "Data info:\n"
#     "- ~24,000 training audio clips (.ogg) in data/train_audio/\n"
#     "- train.csv columns: primary_label, filename, secondary_labels, latitude, longitude, "
#     "scientific_name, common_name, etc.\n"
#     "- 234 target species defined by sample_submission.csv\n"
#     "- Audio is 5-second clips converted to mel spectrograms\n\n"
#     "Start with a simple CNN baseline (Conv2D blocks + GlobalAveragePooling).\n\n"
#     "Here is the starting code to modify:\n"
#     f"```python\n{DEFAULT_SLOT_CODE}```"
# )


# def _build_feedback_prompt(*, stdout, stderr, is_error, metrics, current_code):
#     if is_error:
#         return (
#             "The last run FAILED with this error:\n"
#             f"```\n{_truncate(stderr, 3000)}\n```\n\n"
#             "Fix the bug. Return the corrected get_training_config() and build_model().\n"
#             f"Current code:\n```python\n{current_code}\n```"
#         )
#     metrics_str = ""
#     if metrics:
#         metrics_str = (
#             f"macro_roc_auc = {metrics.get('macro_roc_auc', 'N/A')}\n"
#             f"scored_species = {metrics.get('num_scored_columns', '?')}\n"
#             f"training_samples = {metrics.get('num_samples', '?')}\n"
#         )
#     return (
#         "The last experiment completed successfully.\n\n"
#         f"Results:\n{metrics_str}\n"
#         f"Training output:\n{_truncate(stdout, 2000)}\n\n"
#         "Propose ONE specific improvement to increase macro_roc_auc. Options:\n"
#         "- More/fewer Conv2D layers or filters\n"
#         "- Add BatchNormalization\n"
#         "- Change dropout, learning rate, epochs, batch size\n"
#         "- Increase max_samples\n"
#         "- Change n_mels, n_frames\n"
#         "- Add data augmentation in build_features()\n\n"
#         f"Return the complete updated code.\nCurrent code:\n```python\n{current_code}\n```"
#     )


# # ---------------------------------------------------------------------------
# # Helpers
# # ---------------------------------------------------------------------------

# def _truncate(text, max_chars=4000):
#     return text if len(text) <= max_chars else text[:max_chars] + "\n...[truncated]..."


# def extract_python_code(response):
#     if not response or not response.strip():
#         return ""
#     blocks = re.findall(r"```python\s*(.*?)```", response, re.IGNORECASE | re.DOTALL)
#     if blocks:
#         return blocks[0].strip()
#     blocks = re.findall(r"```(?:\w+)?\s*(.*?)```", response, re.DOTALL)
#     if blocks:
#         return blocks[0].strip()
#     return ""


# def validate_slot_code(code):
#     issues = []
#     try:
#         ast.parse(code)
#     except SyntaxError as e:
#         return [f"SyntaxError: {e}"]
#     if not re.search(r"def\s+build_model\s*\(", code):
#         issues.append("Missing: def build_model(input_shape, num_classes)")
#     if not re.search(r"def\s+get_training_config\s*\(", code):
#         issues.append("Missing: def get_training_config()")
#     if re.search(r"def\s+main\s*\(", code):
#         issues.append("Do NOT define main()")
#     return issues


# def assemble_script(slot_code, *, is_final=False, model_save_path=""):
#     suffix = _make_harness_suffix(is_final=is_final, model_save_path=model_save_path)
#     return f"{HARNESS_PREFIX}\n# ── LLM-generated slots ──\n\n{slot_code.strip()}\n\n{suffix}"


# def _append_eval_wrapper(script, iteration, eval_dir):
#     yt = eval_dir / f"y_true_iter_{iteration}.npy"
#     yp = eval_dir / f"y_pred_iter_{iteration}.npy"
#     return script + f'''

# import numpy as _np
# _yt = _np.asarray(y_train)
# _yp = _np.asarray(model.predict(X_train, verbose=0))
# if _yt.shape != _yp.shape:
#     raise RuntimeError(f"Shape mismatch: y_train={{_yt.shape}} vs y_pred={{_yp.shape}}")
# _np.save("{yt}", _yt)
# _np.save("{yp}", _yp)
# print(f"EVAL_ARTIFACTS_SAVED y_true={yt} y_pred={yp}")
# '''


# def _trim_and_append(messages, role, content):
#     messages.append({"role": role, "content": content})
#     if len(messages) > 6:
#         messages = messages[:2] + messages[-4:]
#     return messages


# def _save_metrics(history, path):
#     path.write_text(json.dumps(history, indent=2), encoding="utf-8")


# # ---------------------------------------------------------------------------
# # Kaggle inference notebook generator
# # ---------------------------------------------------------------------------

# def _generate_kaggle_notebook(slot_code, output_path):
#     ns = {}
#     try:
#         exec(slot_code, ns)
#         cfg = ns.get("get_training_config", lambda: {})()
#     except Exception:
#         cfg = {}

#     sr = cfg.get("sample_rate", 32000)
#     cs = cfg.get("clip_seconds", 5.0)
#     nm = cfg.get("n_mels", 64)
#     nf = cfg.get("n_frames", 128)

#     nb = {
#         "nbformat": 4, "nbformat_minor": 4,
#         "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}},
#         "cells": [
#             {"cell_type": "markdown", "metadata": {}, "source": [
#                 "# BirdCLEF+ 2026 — Inference Notebook\n",
#                 "Auto-generated by the autonomous research agent.\n",
#                 "Upload model.keras as a Kaggle dataset and reference it below."
#             ]},
#             {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
#                 "import os, numpy as np, pandas as pd, librosa, tensorflow as tf\n",
#                 "from pathlib import Path\n",
#                 "\n",
#                 f"SR = {sr}\n",
#                 f"CLIP_SECONDS = {cs}\n",
#                 f"N_MELS = {nm}\n",
#                 f"N_FRAMES = {nf}\n",
#                 "N_FFT = 1024\n",
#                 "HOP_LENGTH = 512\n",
#                 "\n",
#                 "COMP_DIR = '/kaggle/input/birdclef-2026'\n",
#                 "MODEL_DIR = '/kaggle/input/birdclef-model'  # your uploaded model dataset\n",
#             ]},
#             {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
#                 "model = tf.keras.models.load_model(os.path.join(MODEL_DIR, 'model.keras'))\n",
#                 "sample_sub = pd.read_csv(os.path.join(COMP_DIR, 'sample_submission.csv'))\n",
#                 "species_cols = [c for c in sample_sub.columns if c != 'row_id']\n",
#                 "print(f'Model loaded. Species: {len(species_cols)}')\n",
#             ]},
#             {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
#                 "test_dir = Path(COMP_DIR) / 'test_soundscapes'\n",
#                 "test_files = sorted(test_dir.glob('*.ogg')) if test_dir.exists() else []\n",
#                 "print(f'Test soundscapes: {len(test_files)}')\n",
#                 "\n",
#                 "all_rows = []\n",
#                 "seg_samples = SR * CLIP_SECONDS\n",
#                 "\n",
#                 "for fpath in test_files:\n",
#                 "    name = fpath.stem\n",
#                 "    y_full, _ = librosa.load(str(fpath), sr=SR, mono=True)\n",
#                 "    for start in range(0, len(y_full), seg_samples):\n",
#                 "        seg = y_full[start:start+seg_samples]\n",
#                 "        if len(seg) < seg_samples:\n",
#                 "            seg = np.pad(seg, (0, seg_samples - len(seg)))\n",
#                 "        end_sec = (start // seg_samples + 1) * CLIP_SECONDS\n",
#                 "        mel = librosa.feature.melspectrogram(\n",
#                 "            y=seg, sr=SR, n_mels=N_MELS, n_fft=N_FFT, hop_length=HOP_LENGTH, power=2.0)\n",
#                 "        mel_db = librosa.power_to_db(mel, ref=np.max)\n",
#                 "        mel_r = tf.image.resize(mel_db[..., np.newaxis], (N_MELS, N_FRAMES)).numpy().astype(np.float32)\n",
#                 "        preds = model.predict(mel_r[np.newaxis, ...], verbose=0)[0]\n",
#                 "        row = {'row_id': f'{name}_{end_sec}'}\n",
#                 "        for col, p in zip(species_cols, preds):\n",
#                 "            row[col] = float(p)\n",
#                 "        all_rows.append(row)\n",
#                 "\n",
#                 "print(f'Prediction rows: {len(all_rows)}')\n",
#             ]},
#             {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
#                 "sub = pd.DataFrame(all_rows) if all_rows else sample_sub.copy()\n",
#                 "sub = sample_sub[['row_id']].merge(sub, on='row_id', how='left')\n",
#                 "sub[species_cols] = sub[species_cols].fillna(0.0).clip(0.0, 1.0)\n",
#                 "sub.to_csv('/kaggle/working/submission.csv', index=False)\n",
#                 "print(f'Submission saved: {sub.shape}')\n",
#             ]},
#         ]
#     }
#     output_path.write_text(json.dumps(nb, indent=1), encoding="utf-8")


# # ---------------------------------------------------------------------------
# # Final run
# # ---------------------------------------------------------------------------

# def _run_final(*, best_slot_code, executor, evaluator, project_root):
#     sub_dir = project_root / "submission"
#     sub_dir.mkdir(parents=True, exist_ok=True)
#     logs_dir = project_root / "logs"
#     eval_dir = logs_dir / "eval_artifacts"
#     model_path = str(sub_dir / "model.keras")

#     print("\n" + "=" * 60)
#     print("  FINAL RUN: Retraining best model on ALL data")
#     print("=" * 60)

#     script = assemble_script(best_slot_code, is_final=True, model_save_path=model_path)
#     script = _append_eval_wrapper(script, 999, eval_dir)
#     script_path = logs_dir / "final_run.py"
#     script_path.write_text(script, encoding="utf-8")

#     t0 = time.time()
#     result = executor.run_file(script_path)
#     dt = time.time() - t0

#     if result.success:
#         print(f"  SUCCESS ({dt:.1f}s)")
#         yt = eval_dir / "y_true_iter_999.npy"
#         yp = eval_dir / "y_pred_iter_999.npy"
#         if yt.exists() and yp.exists():
#             ev = evaluator.evaluate_from_files(yt, yp)
#             if ev.metrics.get("status") == "success":
#                 print(f"  macro_roc_auc = {ev.metrics['macro_roc_auc']:.6f}")
#                 print(f"  scored_species = {ev.metrics['num_scored_columns']}")
#                 print(f"  samples = {ev.metrics['num_samples']}")

#         if Path(model_path).exists():
#             mb = Path(model_path).stat().st_size / (1024*1024)
#             print(f"  Model: {model_path} ({mb:.1f} MB)")

#         nb_path = sub_dir / "kaggle_inference.ipynb"
#         _generate_kaggle_notebook(best_slot_code, nb_path)
#         print(f"  Kaggle notebook: {nb_path}")

#         (sub_dir / "best_model_code.py").write_text(best_slot_code, encoding="utf-8")

#         print(f"\n  submission/ contents:")
#         for f in sorted(sub_dir.iterdir()):
#             print(f"    {f.name} ({f.stat().st_size/1024:.1f} KB)")
#     else:
#         print(f"  FAILED ({dt:.1f}s)")
#         print(f"  {_truncate(result.stderr, 2000)}")


# # ---------------------------------------------------------------------------
# # Agent loop
# # ---------------------------------------------------------------------------

# def agent_loop(config):
#     project_root = Path(__file__).resolve().parents[1]
#     logs_dir = project_root / "logs"
#     eval_dir = logs_dir / "eval_artifacts"
#     logs_dir.mkdir(exist_ok=True)
#     eval_dir.mkdir(exist_ok=True)

#     llm = LLMClient(provider=config["llm"]["provider"], model=config["llm"]["model"])
#     executor = CodeExecutor(
#         python_executable=config["execution"]["python_executable"],
#         timeout_seconds=config["execution"]["timeout_seconds"],
#     )
#     evaluator = Evaluator(row_id_column_name="row_id")

#     max_iters = config.get("max_iterations", 10)
#     temp = config["llm"].get("temperature", 0.2)
#     current_slot = DEFAULT_SLOT_CODE
#     best_slot = DEFAULT_SLOT_CODE
#     messages = [
#         {"role": "system", "content": SYSTEM_PROMPT},
#         {"role": "user", "content": SEED_PROMPT},
#     ]
#     metrics_history = []
#     best_auc = 0.0
#     consec_fail = 0
#     max_fail = config.get("max_failures_before_stop", 5)

#     print("=" * 60)
#     print("  BirdCLEF Autonomous Research Agent")
#     print("=" * 60)
#     print(f"  Model:      {config['llm']['model']}")
#     print(f"  Iterations: {max_iters}")
#     print(f"  Timeout:    {config['execution']['timeout_seconds']}s")
#     print("=" * 60)

#     for it in range(1, max_iters + 1):
#         print(f"\n{'─'*50}\n  ITERATION {it}/{max_iters}\n{'─'*50}")

#         # 1. Query LLM
#         t0 = time.time()
#         print("Querying LLM...")
#         resp = llm.generate_from_messages(messages=messages, temperature=temp)
#         print(f"LLM responded in {time.time()-t0:.1f}s")

#         # 2. Extract & validate
#         slot = extract_python_code(resp)
#         if not slot:
#             print("ERROR: No code in response")
#             messages = _trim_and_append(messages, "assistant", resp)
#             messages = _trim_and_append(messages, "user",
#                 "No ```python``` block found. Return ONLY code with get_training_config() and build_model().")
#             consec_fail += 1
#             metrics_history.append({"iteration": it, "status": "no_code"})
#             if consec_fail >= max_fail: break
#             continue

#         issues = validate_slot_code(slot)
#         if issues:
#             print(f"Validation: {issues}")
#             messages = _trim_and_append(messages, "assistant", resp)
#             messages = _trim_and_append(messages, "user",
#                 f"Errors: {'; '.join(issues)}. Fix and return corrected code.")
#             consec_fail += 1
#             metrics_history.append({"iteration": it, "status": "validation_failed"})
#             if consec_fail >= max_fail: break
#             continue

#         current_slot = slot

#         # 3. Assemble & execute
#         full = assemble_script(slot)
#         full = _append_eval_wrapper(full, it, eval_dir)
#         sp = logs_dir / f"iteration_{it}.py"
#         sp.write_text(full, encoding="utf-8")
#         (logs_dir / f"slots_{it}.py").write_text(slot, encoding="utf-8")

#         print(f"Executing {sp.name}...")
#         t0 = time.time()
#         result = executor.run_file(sp)
#         dt = time.time() - t0
#         print(f"{'SUCCESS' if result.success else 'FAILED'} ({dt:.1f}s)")

#         # 4. Evaluate
#         em = None
#         if result.success:
#             consec_fail = 0
#             yt = eval_dir / f"y_true_iter_{it}.npy"
#             yp = eval_dir / f"y_pred_iter_{it}.npy"
#             if yt.exists() and yp.exists():
#                 ev = evaluator.evaluate_from_files(yt, yp)
#                 em = ev.metrics
#                 if em.get("status") == "success":
#                     auc = em["macro_roc_auc"]
#                     print(f"  macro_roc_auc = {auc:.6f} | scored = {em['num_scored_columns']}")
#                     if auc > best_auc:
#                         best_auc = auc
#                         best_slot = slot
#                         print(f"  ★ NEW BEST ({best_auc:.6f})")
#                         (logs_dir / "best_slots.py").write_text(slot, encoding="utf-8")
#             metrics_history.append({"iteration": it, "status": "success", "time": round(dt,1),
#                                      "macro_roc_auc": em.get("macro_roc_auc") if em else None})
#         else:
#             consec_fail += 1
#             print(f"  stderr: {_truncate(result.stderr, 200)}")
#             metrics_history.append({"iteration": it, "status": "failed", "time": round(dt,1)})
#             if consec_fail >= max_fail: break

#         # 5. Feedback
#         fb = _build_feedback_prompt(stdout=result.stdout, stderr=result.stderr,
#                                      is_error=not result.success, metrics=em, current_code=current_slot)
#         messages = _trim_and_append(messages, "assistant", resp)
#         messages = _trim_and_append(messages, "user", fb)
#         _save_metrics(metrics_history, logs_dir / "metrics_history.json")

#     # ── Summary ──
#     print(f"\n{'='*60}")
#     ok = sum(1 for m in metrics_history if m["status"] == "success")
#     print(f"  EXPLORATION DONE: {ok}/{len(metrics_history)} successful, best AUC = {best_auc:.6f}")
#     print(f"{'='*60}")

#     (logs_dir / "conversation_history.json").write_text(json.dumps(messages, indent=2), encoding="utf-8")

#     # ── Final run on ALL data ──
#     if best_auc > 0:
#         _run_final(best_slot_code=best_slot, executor=executor, evaluator=evaluator, project_root=project_root)
#     else:
#         print("\nNo successful iterations — skipping final run.")


# def main():
#     project_root = Path(__file__).resolve().parents[1]
#     config = load_config(project_root / "configs" / "agent_config.json")
#     agent_loop(config)

# if __name__ == "__main__":
#     main()


"""
Autonomous BirdCLEF Research Agent — Structured Search
========================================================
Phase 0: Baseline creation (generate + verify initial working model)
Phase 1: Linear search (coordinate descent — one dimension at a time, coarse then zoom)
Phase 2: Random search (random combos → LLM analysis → focused exploitation → tweaks)
Phase 3: Final training on best overall config + Kaggle notebook
"""
 
from __future__ import annotations
 
import inspect
import json
import math
import random
import re
import ast
import time
from pathlib import Path
 
import numpy as np
 
if __package__:
    from .code_executor import CodeExecutor
    from .evaluator import Evaluator
    from .llm_client import LLMClient
else:
    from code_executor import CodeExecutor
    from evaluator import Evaluator
    from llm_client import LLMClient
 
 
# ═══════════════════════════════════════════════════════════════════════════
# DEFAULT PARAMETERS & SEARCH SPACE
# ═══════════════════════════════════════════════════════════════════════════
 
DEFAULT_PARAMS = {
    "depth": 3,
    "filters_base": 32,
    "filter_pattern": "doubling",
    "dropout": 0.3,
    "batch_norm": False,
    "residuals": False,
    "optimizer": "adam",
    "learning_rate": 1e-3,
    "batch_size": 32,
    "n_mels": 64,
    "n_frames": 128,
}
 
# Ordered by impact tier (Tier 1 searched first)
SEARCH_DIMENSIONS = [
    # --- Tier 1: High impact ---
    {"name": "depth",          "coarse": [1, 2, 3, 4, 6, 8, 12, 15, 20], "type": "int",         "zoom": True},
    {"name": "filters_base",   "coarse": [8, 16, 32, 64, 128],           "type": "int",         "zoom": True},
    {"name": "filter_pattern", "coarse": ["constant", "doubling"],        "type": "categorical", "zoom": False},
    {"name": "learning_rate",  "coarse": [1e-1, 5e-2, 1e-2, 5e-3, 1e-3, 5e-4, 1e-4], "type": "log_float", "zoom": True},
    # --- Tier 2: Medium impact ---
    {"name": "residuals",      "coarse": [False, True],                   "type": "bool",        "zoom": False},
    {"name": "batch_norm",     "coarse": [False, True],                   "type": "bool",        "zoom": False},
    {"name": "optimizer",      "coarse": ["adam", "sgd_momentum"],        "type": "categorical", "zoom": False},
    {"name": "n_mels",         "coarse": [32, 64, 128],                   "type": "int",         "zoom": True},
    {"name": "n_frames",       "coarse": [64, 128, 256],                  "type": "int",         "zoom": True},
    # --- Tier 3: Lower impact ---
    {"name": "dropout",        "coarse": [0.0, 0.1, 0.2, 0.3, 0.4, 0.5], "type": "float",       "zoom": False},
    {"name": "batch_size",     "coarse": [8, 16, 32, 64, 128],            "type": "int",         "zoom": False},
]
 
 
# ═══════════════════════════════════════════════════════════════════════════
# HARNESS (fixed data-loading / training / evaluation wrapper)
# ═══════════════════════════════════════════════════════════════════════════
 
HARNESS_PREFIX = """
from __future__ import annotations
import os, sys, inspect
from pathlib import Path
import numpy as np
import librosa
import tensorflow as tf
 
_SCRIPT_PATH = Path(__file__).resolve()
_PROJECT_ROOT = None
for _cand in [_SCRIPT_PATH.parent] + list(_SCRIPT_PATH.parents):
    if (_cand / "src").exists() and (_cand / "configs").exists():
        _PROJECT_ROOT = _cand
        break
if _PROJECT_ROOT is None:
    # Fallback for unexpected layouts.
    _PROJECT_ROOT = _SCRIPT_PATH.parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))
os.chdir(_PROJECT_ROOT)
os.environ.setdefault("BIRDCLEF_DATA_DIR", str(_PROJECT_ROOT / "data"))
 
from src.data_io import (
    load_core_tables,
    resolve_birdclef_paths,
    species_columns_from_sample_submission,
    validate_required_files,
)
 
def _default_load_mel(audio_path, sample_rate, clip_seconds, n_mels, n_frames):
    target_len = int(sample_rate * clip_seconds)
    wav, _ = librosa.load(str(audio_path), sr=sample_rate, mono=True, duration=clip_seconds)
    if len(wav) < target_len:
        wav = np.pad(wav, (0, target_len - len(wav)))
    else:
        wav = wav[:target_len]
    mel = librosa.feature.melspectrogram(
        y=wav, sr=sample_rate, n_mels=n_mels, n_fft=1024, hop_length=512, power=2.0
    )
    mel_db = librosa.power_to_db(mel, ref=np.max)
    mel_resized = tf.image.resize(mel_db[..., np.newaxis], (n_mels, n_frames)).numpy()
    return mel_resized.astype(np.float32)
""".strip()
 
 
def _make_harness_suffix(*, is_final=False, model_save_path=""):
    if is_final:
        max_line = "    max_samples = None  # FINAL RUN: use ALL data"
        save_block = (
            f'\n    _mp = Path("{model_save_path}")\n'
            "    _mp.parent.mkdir(parents=True, exist_ok=True)\n"
            "    model.save(_mp)\n"
            '    print(f"MODEL_SAVED: {_mp}")\n'
        )
    else:
        max_line = '    max_samples = cfg.get("max_samples", 300)'
        save_block = ""
 
    return f"""
def main():
    global model, X_train, y_train
    tf.keras.utils.set_random_seed(42)
    cfg = get_training_config()
    cfg.setdefault("optimizer", "adam")
{max_line}
    sample_rate   = cfg.get("sample_rate", 32000)
    clip_seconds  = cfg.get("clip_seconds", 5.0)
    n_mels        = cfg.get("n_mels", 64)
    n_frames      = cfg.get("n_frames", 128)
    epochs        = cfg.get("epochs", 3)
    batch_size    = cfg.get("batch_size", 32)
    learning_rate = cfg.get("learning_rate", 1e-3)
 
    optimizer_name = cfg.get("optimizer", "adam")
    if optimizer_name == "sgd_momentum":
        _opt = tf.keras.optimizers.SGD(learning_rate=learning_rate, momentum=0.9)
    else:
        _opt = tf.keras.optimizers.Adam(learning_rate=learning_rate)
 
    paths = resolve_birdclef_paths()
    missing = validate_required_files(paths)
    if missing:
        raise FileNotFoundError(f"Missing files: {{missing}}")
 
    tables = load_core_tables(paths)
    train_df = tables["train"]
    sample_sub = tables["sample_submission"]
    species_cols = species_columns_from_sample_submission(sample_sub)
    sp2i = {{s: i for i, s in enumerate(species_cols)}}
 
    lcol = "primary_label" if "primary_label" in train_df.columns else "species_code"
    fcol = "filename" if "filename" in train_df.columns else "filepath"
    mel_fn = _default_load_mel
    if "build_features" in globals() and callable(build_features):
        try:
            sig = inspect.signature(build_features)
            if len(sig.parameters) == 5:
                mel_fn = build_features
        except Exception:
            pass
 
    X_items, y_items = [], []
    total = len(train_df)
    for i, row in enumerate(train_df.itertuples(index=False)):
        label = str(getattr(row, lcol))
        rel = getattr(row, fcol)
        if label not in sp2i:
            continue
        ap = paths.train_audio_dir / str(rel)
        if not ap.exists():
            continue
        try:
            mel = mel_fn(ap, sample_rate, clip_seconds, n_mels, n_frames)
        except Exception:
            continue
        yv = np.zeros(len(species_cols), dtype=np.float32)
        yv[sp2i[label]] = 1.0
        X_items.append(mel)
        y_items.append(yv)
        if max_samples and len(X_items) >= max_samples:
            break
        if len(X_items) % 500 == 0:
            print(f"  Loaded {{len(X_items)}} samples (row {{i+1}}/{{total}})...")
 
    if not X_items:
        raise RuntimeError("No samples loaded.")
    X_train = np.stack(X_items, dtype=np.float32)
    y_train = np.stack(y_items, dtype=np.float32)
    print(f"DATA: X_train={{X_train.shape}}, y_train={{y_train.shape}}")
 
    model = build_model(X_train.shape[1:], len(species_cols))
    model.compile(optimizer=_opt, loss="binary_crossentropy")
    model.summary()
    history = model.fit(X_train, y_train, epochs=epochs, batch_size=min(batch_size, len(X_train)), verbose=1)
    print(f"TRAIN_LOSS: {{history.history['loss'][-1]:.6f}}")
{save_block}
    y_pred = model.predict(X_train, verbose=0).astype(np.float32)
    mean_pred = y_pred.mean(axis=0)
    sub_df = sample_sub.copy()
    for ic, col in enumerate(species_cols):
        sub_df[col] = float(mean_pred[ic])
    sub_path = Path("submission/submission_generated.csv")
    sub_path.parent.mkdir(parents=True, exist_ok=True)
    sub_df.to_csv(sub_path, index=False)
    print(f"SUBMISSION: {{sub_path}}")
 
if __name__ == "__main__":
    main()
"""
 
 
# ═══════════════════════════════════════════════════════════════════════════
# PARAMETRIC CODE GENERATION
# ═══════════════════════════════════════════════════════════════════════════
 
def _compute_filters_list(depth, filters_base, filter_pattern):
    filters = []
    for i in range(depth):
        if filter_pattern == "constant":
            f = filters_base
        elif filter_pattern == "doubling":
            f = filters_base * (2 ** min(i, 4))
        else:
            f = filters_base
        filters.append(min(f, 512))
    return filters
 
 
def _compute_max_pools(depth, n_mels, n_frames):
    min_spatial = min(n_mels, n_frames)
    if min_spatial < 4:
        return 0
    return min(depth, max(1, int(math.log2(min_spatial)) - 1))
 
 
def generate_slot_code(params):
    """Generate get_training_config() + build_model() from a parameter dict."""
    d = params
    filters_list = _compute_filters_list(d["depth"], d["filters_base"], d["filter_pattern"])
    max_pools = _compute_max_pools(d["depth"], d["n_mels"], d["n_frames"])
 
    return f'''def get_training_config():
    return {{
        "max_samples": {d.get("max_samples", 300)},
        "sample_rate": 32000,
        "clip_seconds": 5.0,
        "n_mels": {d["n_mels"]},
        "n_frames": {d["n_frames"]},
        "epochs": {d.get("epochs", 3)},
        "batch_size": {d["batch_size"]},
        "learning_rate": {d["learning_rate"]},
        "optimizer": "{d["optimizer"]}",
    }}
 
 
def build_model(input_shape, num_classes):
    import tensorflow as tf
    filters_list = {filters_list}
    max_pools = {max_pools}
    use_batch_norm = {d["batch_norm"]}
    use_residuals = {d["residuals"]}
    dropout_rate = {d["dropout"]}
 
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    for i, filters in enumerate(filters_list):
        shortcut = x
        x = tf.keras.layers.Conv2D(filters, (3, 3), padding="same")(x)
        if use_batch_norm:
            x = tf.keras.layers.BatchNormalization()(x)
        x = tf.keras.layers.Activation("relu")(x)
        if i < max_pools:
            x = tf.keras.layers.MaxPooling2D((2, 2))(x)
        if use_residuals and i > 0:
            sc_filters = tf.keras.backend.int_shape(x)[-1]
            shortcut = tf.keras.layers.Conv2D(sc_filters, (1, 1), padding="same")(shortcut)
            if i < max_pools:
                shortcut = tf.keras.layers.MaxPooling2D((2, 2))(shortcut)
            if tf.keras.backend.int_shape(x) == tf.keras.backend.int_shape(shortcut):
                x = tf.keras.layers.Add()([x, shortcut])
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    if dropout_rate > 0:
        x = tf.keras.layers.Dropout(dropout_rate)(x)
    x = tf.keras.layers.Dense(num_classes, activation="sigmoid")(x)
    model = tf.keras.Model(inputs, x)
    return model
'''
 
 
def describe_params(params):
    parts = [
        f"depth={params.get('depth','?')}",
        f"filt={params.get('filters_base','?')}-{params.get('filter_pattern','?')}",
        f"lr={params.get('learning_rate','?')}",
        str(params.get("optimizer", "?")),
        f"drop={params.get('dropout','?')}",
        f"BN={'Y' if params.get('batch_norm') else 'N'}",
        f"res={'Y' if params.get('residuals') else 'N'}",
        f"mels={params.get('n_mels','?')}",
        f"frames={params.get('n_frames','?')}",
        f"bs={params.get('batch_size','?')}",
    ]
    return " | ".join(parts)
 
 
# ═══════════════════════════════════════════════════════════════════════════
# UTILITY FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════
 
def _truncate(text, max_chars=4000):
    if not text:
        return ""
    return text if len(text) <= max_chars else text[:max_chars] + "\n...[truncated]..."
 
def _save_json(data, path):
    path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
 
def _fmt_score(v):
    return f"{v:.6f}" if isinstance(v, (int, float)) else "N/A"
 
def assemble_script(slot_code, *, is_final=False, model_save_path=""):
    suffix = _make_harness_suffix(is_final=is_final, model_save_path=model_save_path)
    return f"{HARNESS_PREFIX}\n\n# --- GENERATED MODEL CODE ---\n{slot_code.strip()}\n\n{suffix}\n"
 
def _append_eval_wrapper(script, run_id, eval_dir):
    yt = eval_dir / f"y_true_{run_id}.npy"
    yp = eval_dir / f"y_pred_{run_id}.npy"
    return script + f"""
 
import numpy as _np
_yt = _np.asarray(y_train)
_yp = _np.asarray(model.predict(X_train, verbose=0))
if _yt.shape != _yp.shape:
    raise RuntimeError(f"Shape mismatch: y_train={{_yt.shape}} vs y_pred={{_yp.shape}}")
_np.save(r\"{yt}\", _yt)
_np.save(r\"{yp}\", _yp)
print("EVAL_ARTIFACTS_SAVED")
"""
 
def extract_python_code(response):
    if not response or not response.strip():
        return ""
    blocks = re.findall(r"```python\s*(.*?)```", response, re.IGNORECASE | re.DOTALL)
    if blocks:
        return blocks[0].strip()
    blocks = re.findall(r"```(?:\w+)?\s*(.*?)```", response, re.DOTALL)
    return blocks[0].strip() if blocks else ""
 
def validate_slot_code(code):
    try:
        tree = ast.parse(code)
    except Exception as e:
        return [str(e)]
    if "build_model" not in code:
        return ["Missing build_model"]
    if "get_training_config" not in code:
        return ["Missing get_training_config"]
    allowed = (ast.Import, ast.ImportFrom, ast.FunctionDef, ast.AsyncFunctionDef,
               ast.Assign, ast.AnnAssign, ast.ClassDef)
    for node in tree.body:
        if isinstance(node, ast.Expr) and isinstance(getattr(node, "value", None), ast.Constant):
            if isinstance(node.value.value, str):
                continue
        if not isinstance(node, allowed):
            return ["Top-level executable code not allowed."]
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "build_features":
            if len(node.args.args) != 5:
                return ["build_features must have 5 params."]
    return []
 
GENERATION_SYSTEM_PROMPT = (
    "You are an ML research assistant for BirdCLEF experiments.\n"
    "Return ONLY one ```python``` code block and nothing else.\n"
    "Rules:\n"
    "- Define exactly get_training_config() and build_model(input_shape, num_classes)\n"
    "- Optional build_features(audio_path, sample_rate, clip_seconds, n_mels, n_frames)\n"
    "- Do NOT define main()\n"
    "- No executable top-level statements except imports/assignments/function defs\n"
    "- Final layer must be Dense(num_classes, activation='sigmoid')\n"
    "- Compile with binary_crossentropy\n"
)
 
SAFE_BASELINE_SLOT_CODE = """def get_training_config():
    return {
        "max_samples": 300,
        "sample_rate": 32000,
        "clip_seconds": 5.0,
        "n_mels": 64,
        "n_frames": 128,
        "epochs": 3,
        "batch_size": 32,
        "learning_rate": 1e-3,
        "optimizer": "adam",
    }


def build_model(input_shape, num_classes):
    import tensorflow as tf
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=input_shape),
        tf.keras.layers.Conv2D(16, (3, 3), activation="relu", padding="same"),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(64, (3, 3), activation="relu", padding="same"),
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(num_classes, activation="sigmoid"),
    ])
    return model
"""

 
# ═══════════════════════════════════════════════════════════════════════════
# EXPERIMENT RUNNER (with LLM auto-fix on failure)
# ═══════════════════════════════════════════════════════════════════════════
 
def run_experiment(slot_code, run_id, code_dir, eval_dir, executor, evaluator):
    """Run a single experiment. Returns (metrics_or_None, exec_result)."""
    script = assemble_script(slot_code)
    script = _append_eval_wrapper(script, run_id, eval_dir)
    script_path = code_dir / f"{run_id}.py"
    script_path.write_text(script, encoding="utf-8")
    (code_dir / f"{run_id}_slot.py").write_text(slot_code, encoding="utf-8")
 
    result = executor.run_file(script_path)
    if not result.success:
        return None, result
 
    yt = eval_dir / f"y_true_{run_id}.npy"
    yp = eval_dir / f"y_pred_{run_id}.npy"
    if yt.exists() and yp.exists():
        ev = evaluator.evaluate_from_files(yt, yp)
        return ev.metrics, result
    return None, result
 
def _clean_error_text(stderr: str) -> str:
    if not stderr:
        return ""
    lines = stderr.splitlines()
    filtered = [ln for ln in lines if "NotOpenSSLWarning" not in ln and "urllib3/__init__.py:35" not in ln]
    text = "\n".join(filtered).strip()
    return text if text else stderr.strip()

 
def run_experiment_until_success(slot_code, run_id, code_dir, eval_dir,
                                 executor, evaluator, llm, temperature, max_attempts=5, use_llm_fixes=True):
    """Run experiment, auto-fix with LLM on failure."""
    current_slot = slot_code
    for attempt in range(1, max_attempts + 1):
        metrics, result = run_experiment(
            current_slot, f"{run_id}_a{attempt}", code_dir, eval_dir, executor, evaluator
        )
        if metrics and metrics.get("status") == "success":
            if attempt > 1:
                print(f"    Fixed after {attempt} attempts")
            return current_slot, metrics, result, attempt
 
        error_text = _clean_error_text(result.stderr) if not result.success else "No valid metrics produced."
        err_path = code_dir / f"{run_id}_a{attempt}_stderr.log"
        err_path.write_text(result.stderr or "", encoding="utf-8")
        if attempt == max_attempts:
            print(f"    Failed all {max_attempts} attempts. Error: {_truncate(error_text, 200)}")
            return current_slot, None, result, attempt
 
        if not use_llm_fixes:
            print(f"    Attempt {attempt} failed (LLM fixes disabled for this run).")
            return current_slot, None, result, attempt

        print(f"    Attempt {attempt} failed, requesting LLM fix...")
        fix_prompt = (
            f"The model code failed.\nError:\n{_truncate(error_text, 3000)}\n\n"
            f"Current code:\n```python\n{current_slot}\n```\n\n"
            "Fix it. Return ONLY a python code block with get_training_config() and build_model()."
        )
        resp = llm.generate_from_messages(
            messages=[{"role": "system", "content": GENERATION_SYSTEM_PROMPT},
                      {"role": "user", "content": fix_prompt}],
            temperature=temperature,
        )
        candidate = extract_python_code(resp)
        issues = validate_slot_code(candidate) if candidate else ["No code found."]
        if not issues:
            current_slot = candidate
        else:
            print(f"    LLM fix invalid: {issues}")
 
    return current_slot, None, result, max_attempts
 
 
# ═══════════════════════════════════════════════════════════════════════════
# PHASE 0: BASELINE
# ═══════════════════════════════════════════════════════════════════════════
 
def _run_baseline(executor, evaluator, llm, temperature, dirs, search_cfg):
    print("\n" + "=" * 60)
    print("  PHASE 0: BASELINE VERIFICATION")
    print("=" * 60)
 
    params = dict(DEFAULT_PARAMS)
    params["max_samples"] = search_cfg["cheap"]["max_samples"]
    params["epochs"] = search_cfg["cheap"]["epochs"]
    slot_code = generate_slot_code(params)

    # Stage A: deterministic generated baseline, no LLM fixes.
    slot_code, metrics, result, attempts = run_experiment_until_success(
        slot_code, "baseline_gen", dirs["baseline_codes"], dirs["eval"],
        executor, evaluator, llm, temperature, max_attempts=1, use_llm_fixes=False,
    )

    # Stage B: hardcoded safe baseline, no LLM fixes.
    if not (metrics and metrics.get("status") == "success"):
        print("  Generated baseline failed. Trying safe baseline template...")
        slot_code, metrics, result, attempts_b = run_experiment_until_success(
            SAFE_BASELINE_SLOT_CODE, "baseline_safe", dirs["baseline_codes"], dirs["eval"],
            executor, evaluator, llm, temperature, max_attempts=1, use_llm_fixes=False,
        )
        attempts += attempts_b

    # Stage C: only then allow iterative LLM fixes.
    if not (metrics and metrics.get("status") == "success"):
        print("  Safe baseline failed. Falling back to LLM auto-fix loop...")
        slot_code, metrics, result, attempts_c = run_experiment_until_success(
            slot_code, "baseline_fix", dirs["baseline_codes"], dirs["eval"],
            executor, evaluator, llm, temperature, max_attempts=5, use_llm_fixes=True,
        )
        attempts += attempts_c

    auc = metrics["macro_roc_auc"] if metrics and metrics.get("status") == "success" else None
    entry = {"params": params, "score": auc, "status": "success" if auc else "failed", "attempts": attempts,
             "description": describe_params(params)}
    _save_json(entry, dirs["logs"] / "baseline_result.json")
    print(f"\n  Baseline AUC = {_fmt_score(auc)} (attempts={attempts})")
    return slot_code, entry
 
 
# ═══════════════════════════════════════════════════════════════════════════
# PHASE 1: LINEAR SEARCH
# ═══════════════════════════════════════════════════════════════════════════
 
def _compute_zoom_values(dim, winner):
    coarse = dim["coarse"]
    dt = dim["type"]
    if dt in ("bool", "categorical") or not dim.get("zoom"):
        return []
    idx = coarse.index(winner) if winner in coarse else 0
    lo = coarse[max(0, idx - 1)]
    hi = coarse[min(len(coarse) - 1, idx + 1)]
    if lo == hi:
        return []
    if dt == "int":
        step = max(1, (int(hi) - int(lo)) // 5)
        return [v for v in range(int(lo), int(hi) + 1, step) if v != winner and v not in coarse][:5]
    elif dt == "float":
        return [round(v, 3) for v in np.linspace(lo, hi, 6) if abs(v - winner) > 0.01][:4]
    elif dt == "log_float":
        cands = np.logspace(np.log10(max(lo, 1e-8)), np.log10(max(hi, 1e-8)), 6)
        return [round(v, 7) for v in cands if abs(v - winner) / max(winner, 1e-10) > 0.05][:4]
    return []
 
 
def _run_linear_search(baseline_slot, executor, evaluator, llm, temperature, dirs, search_cfg):
    print("\n" + "=" * 60)
    print("  PHASE 1: LINEAR SEARCH (coordinate descent)")
    print("=" * 60)
 
    budget = search_cfg.get("linear_budget", 75)
    s, e = search_cfg["cheap"]["max_samples"], search_cfg["cheap"]["epochs"]
    current_best = dict(DEFAULT_PARAMS)
    all_results = []
    rc = 0
    cf = 0
 
    for dim in SEARCH_DIMENSIONS:
        dn = dim["name"]
        if rc >= budget:
            break
        print(f"\n  ── Sweeping: {dn} ({dim['coarse']}) ──")
        dim_results = []
 
        for val in dim["coarse"]:
            if rc >= budget:
                break
            rc += 1
            p = dict(current_best); p[dn] = val; p["max_samples"] = s; p["epochs"] = e
            slot = generate_slot_code(p)
            rid = f"L{rc:03d}_{dn}"
            slot, metrics, result, att = run_experiment_until_success(
                slot, rid, dirs["linear_codes"], dirs["eval"], executor, evaluator, llm, temperature)
            auc = metrics["macro_roc_auc"] if metrics and metrics.get("status") == "success" else None
            entry = {"run_id": rid, "dimension": dn, "value": val, "search_type": "coarse",
                     "params": {k: v for k, v in p.items() if k not in ("max_samples", "epochs")},
                     "macro_roc_auc": auc, "success": auc is not None, "attempts": att,
                     "description": describe_params(p)}
            all_results.append(entry); dim_results.append(entry)
            print(f"    {dn}={val} → {_fmt_score(auc)} (att={att})")
            if not entry["success"]:
                cf += 1
                if cf >= 5: print(f"\n  ⚠ {cf} consecutive failures on {dn}={val}")
            else:
                cf = 0
 
        ok = [r for r in dim_results if r["success"]]
        if not ok:
            print(f"  No successful runs for {dn}. Keeping default={current_best[dn]}")
            continue
        coarse_best = max(ok, key=lambda r: r["macro_roc_auc"])
        cbv = coarse_best["value"]
        print(f"  Coarse winner: {dn}={cbv} (AUC={coarse_best['macro_roc_auc']:.6f})")
 
        zoom_vals = _compute_zoom_values(dim, cbv)
        if zoom_vals:
            print(f"  Zooming: {zoom_vals}")
            for val in zoom_vals:
                if rc >= budget:
                    break
                rc += 1
                p = dict(current_best); p[dn] = val; p["max_samples"] = s; p["epochs"] = e
                slot = generate_slot_code(p)
                rid = f"L{rc:03d}_{dn}_zoom"
                slot, metrics, result, att = run_experiment_until_success(
                    slot, rid, dirs["linear_codes"], dirs["eval"], executor, evaluator, llm, temperature)
                auc = metrics["macro_roc_auc"] if metrics and metrics.get("status") == "success" else None
                entry = {"run_id": rid, "dimension": dn, "value": val, "search_type": "zoom",
                         "params": {k: v for k, v in p.items() if k not in ("max_samples", "epochs")},
                         "macro_roc_auc": auc, "success": auc is not None, "attempts": att,
                         "description": describe_params(p)}
                all_results.append(entry); dim_results.append(entry)
                print(f"    {dn}={val} (zoom) → {_fmt_score(auc)}")
                cf = 0 if entry["success"] else cf + 1
 
        all_ok = [r for r in dim_results if r["success"]]
        if all_ok:
            winner = max(all_ok, key=lambda r: r["macro_roc_auc"])
            current_best[dn] = winner["value"]
            print(f"  ★ Locked {dn}={winner['value']} (AUC={winner['macro_roc_auc']:.6f})")
 
    _save_json(all_results, dirs["logs"] / "linear.json")
    _save_json(current_best, dirs["logs"] / "linear_best_params.json")
    tok = sum(1 for r in all_results if r["success"])
    print(f"\n  Linear done: {rc} iters, {tok} successful")
    print(f"  Best: {describe_params(current_best)}")
    return all_results, current_best
 
 
# ═══════════════════════════════════════════════════════════════════════════
# PHASE 2: RANDOM SEARCH
# ═══════════════════════════════════════════════════════════════════════════
 
def _sample_random_params(rng):
    return {
        "depth": int(rng.choice([1,2,3,4,5,6,8,10,12,15,20])),
        "filters_base": int(rng.choice([8,16,24,32,48,64,96,128])),
        "filter_pattern": str(rng.choice(["constant","doubling"])),
        "learning_rate": float(10 ** rng.uniform(-4, -1)),
        "optimizer": str(rng.choice(["adam","sgd_momentum"])),
        "dropout": round(float(rng.uniform(0.0, 0.6)), 2),
        "batch_norm": bool(rng.choice([True, False])),
        "residuals": bool(rng.choice([True, False])),
        "batch_size": int(rng.choice([8,16,32,64,128])),
        "n_mels": int(rng.choice([32,64,96,128])),
        "n_frames": int(rng.choice([64,128,192,256])),
    }
 
def _tweak_params(base, rng):
    p = dict(base)
    dims = rng.choice(["depth","filters_base","learning_rate","dropout","batch_size","n_mels","n_frames"],
                       size=int(rng.choice([1,2])), replace=False)
    for d in dims:
        if d == "depth":        p["depth"] = max(1, p["depth"] + int(rng.choice([-2,-1,1,2])))
        elif d == "filters_base": p["filters_base"] = int(rng.choice([8,16,24,32,48,64,96,128]))
        elif d == "learning_rate": p["learning_rate"] = float(np.clip(p["learning_rate"] * 10**rng.uniform(-0.5,0.5), 1e-5, 0.5))
        elif d == "dropout":    p["dropout"] = round(float(np.clip(p["dropout"]+rng.uniform(-0.15,0.15), 0, 0.7)), 2)
        elif d == "batch_size": p["batch_size"] = int(rng.choice([8,16,32,64,128]))
        elif d == "n_mels":     p["n_mels"] = int(rng.choice([32,64,96,128]))
        elif d == "n_frames":   p["n_frames"] = int(rng.choice([64,128,192,256]))
    return p
 
def _analyze_random_results(results, llm, temperature):
    ok = [r for r in results if r.get("success") and r.get("macro_roc_auc")]
    if len(ok) < 3:
        return None
    ok.sort(key=lambda r: r["macro_roc_auc"], reverse=True)
    lines = ["rank | AUC      | description", "-"*80]
    for i, r in enumerate(ok[:20]):
        lines.append(f"{i+1:4d} | {r['macro_roc_auc']:.6f} | {r['description']}")
    prompt = (
        "Results from random architecture search for bird audio classification.\n\n"
        + "\n".join(lines) + "\n\n"
        "Return ONLY a JSON object with narrowed ranges for focused search:\n"
        '{"depth":[min,max],"filters_base":[min,max],"learning_rate":[min,max],'
        '"dropout":[min,max],"batch_norm":true/false/null,"residuals":true/false/null,'
        '"optimizer":"adam"/"sgd_momentum"/null,"n_mels":[min,max],"n_frames":[min,max],'
        '"batch_size":[min,max],"filter_pattern":"constant"/"doubling"/null,'
        '"analysis":"brief summary"}'
    )
    resp = llm.generate_from_messages(
        messages=[{"role":"system","content":"Return ONLY valid JSON."},{"role":"user","content":prompt}],
        temperature=temperature)
    try:
        m = re.search(r'\{.*\}', resp, re.DOTALL)
        if m: return json.loads(m.group())
    except: pass
    return None
 
def _sample_narrowed(ranges, rng):
    p = _sample_random_params(rng)
    if not ranges: return p
    def _pick(key, choices):
        if key in ranges and isinstance(ranges[key], list) and len(ranges[key]) == 2:
            f = [v for v in choices if ranges[key][0] <= v <= ranges[key][1]]
            if f: return int(rng.choice(f))
        return p[key]
    p["depth"] = _pick("depth", [1,2,3,4,5,6,8,10,12,15,20])
    p["filters_base"] = _pick("filters_base", [8,16,24,32,48,64,96,128])
    p["batch_size"] = _pick("batch_size", [8,16,32,64,128])
    p["n_mels"] = _pick("n_mels", [32,64,96,128])
    p["n_frames"] = _pick("n_frames", [64,128,192,256])
    if "learning_rate" in ranges and isinstance(ranges["learning_rate"], list) and len(ranges["learning_rate"])==2:
        p["learning_rate"] = float(10**rng.uniform(np.log10(max(ranges["learning_rate"][0],1e-6)),
                                                    np.log10(min(ranges["learning_rate"][1],1.0))))
    if "dropout" in ranges and isinstance(ranges["dropout"], list) and len(ranges["dropout"])==2:
        p["dropout"] = round(float(rng.uniform(ranges["dropout"][0], ranges["dropout"][1])), 2)
    for key in ("batch_norm","residuals"):
        if key in ranges and ranges[key] is not None: p[key] = bool(ranges[key])
    for key in ("optimizer","filter_pattern"):
        if key in ranges and ranges[key] is not None: p[key] = str(ranges[key])
    return p
 
 
def _run_random_search(baseline_slot, executor, evaluator, llm, temperature, dirs, search_cfg):
    print("\n" + "=" * 60)
    print("  PHASE 2: RANDOM SEARCH")
    print("=" * 60)
 
    budget = search_cfg.get("random_budget", 50)
    s, e = search_cfg["cheap"]["max_samples"], search_cfg["cheap"]["epochs"]
    explore_count = min(20, budget)
    rng = np.random.default_rng(search_cfg.get("random_seed", 42))
    all_results = []
    rc = 0
 
    # Sub-phase A: Pure random
    print(f"\n  ── A: {explore_count} random experiments ──")
    for _ in range(explore_count):
        if rc >= budget: break
        rc += 1
        p = _sample_random_params(rng); p["max_samples"] = s; p["epochs"] = e
        slot = generate_slot_code(p)
        rid = f"R{rc:03d}_explore"
        slot, metrics, result, att = run_experiment_until_success(
            slot, rid, dirs["random_codes"], dirs["eval"], executor, evaluator, llm, temperature)
        auc = metrics["macro_roc_auc"] if metrics and metrics.get("status") == "success" else None
        entry = {"run_id": rid, "search_type": "explore",
                 "params": {k:v for k,v in p.items() if k not in ("max_samples","epochs")},
                 "macro_roc_auc": auc, "success": auc is not None, "attempts": att,
                 "description": describe_params(p)}
        all_results.append(entry)
        print(f"    R{rc:03d}: {_fmt_score(auc)} | {describe_params(p)}")
 
    # LLM analysis
    print(f"\n  ── Analyzing results with LLM ──")
    narrowed = _analyze_random_results(all_results, llm, temperature)
    if narrowed:
        print(f"  Analysis: {narrowed.get('analysis','')[:300]}")
        _save_json(narrowed, dirs["logs"] / "random_llm_analysis.json")
    else:
        print("  LLM analysis failed. Using top-K exploitation.")
 
    rem = budget - rc
 
    # Sub-phase B: Focused
    fc = min(rem // 2, 15)
    if fc > 0:
        print(f"\n  ── B: {fc} focused experiments ──")
        for _ in range(fc):
            if rc >= budget: break
            rc += 1
            p = _sample_narrowed(narrowed, rng); p["max_samples"] = s; p["epochs"] = e
            slot = generate_slot_code(p)
            rid = f"R{rc:03d}_focused"
            slot, metrics, result, att = run_experiment_until_success(
                slot, rid, dirs["random_codes"], dirs["eval"], executor, evaluator, llm, temperature)
            auc = metrics["macro_roc_auc"] if metrics and metrics.get("status") == "success" else None
            all_results.append({"run_id": rid, "search_type": "focused",
                "params": {k:v for k,v in p.items() if k not in ("max_samples","epochs")},
                "macro_roc_auc": auc, "success": auc is not None, "attempts": att,
                "description": describe_params(p)})
            print(f"    R{rc:03d}: {_fmt_score(auc)} | {describe_params(p)}")
 
    # Sub-phase C: Tweak top-K
    rem = budget - rc
    ok = sorted([r for r in all_results if r.get("success") and r.get("macro_roc_auc")],
                key=lambda r: r["macro_roc_auc"], reverse=True)[:5]
    if ok and rem > 0:
        tc = min(rem, len(ok) * 3)
        print(f"\n  ── C: {tc} tweaks of top configs ──")
        for i in range(tc):
            if rc >= budget: break
            rc += 1
            p = _tweak_params(ok[i % len(ok)]["params"], rng); p["max_samples"] = s; p["epochs"] = e
            slot = generate_slot_code(p)
            rid = f"R{rc:03d}_tweak"
            slot, metrics, result, att = run_experiment_until_success(
                slot, rid, dirs["random_codes"], dirs["eval"], executor, evaluator, llm, temperature)
            auc = metrics["macro_roc_auc"] if metrics and metrics.get("status") == "success" else None
            all_results.append({"run_id": rid, "search_type": "tweak",
                "params": {k:v for k,v in p.items() if k not in ("max_samples","epochs")},
                "macro_roc_auc": auc, "success": auc is not None, "attempts": att,
                "description": describe_params(p)})
            print(f"    R{rc:03d}: {_fmt_score(auc)} | {describe_params(p)}")
 
    _save_json(all_results, dirs["logs"] / "random_results.json")
    all_ok = [r for r in all_results if r.get("success") and r.get("macro_roc_auc")]
    best = max(all_ok, key=lambda r: r["macro_roc_auc"]) if all_ok else None
    print(f"\n  Random done: {rc} iters, {len(all_ok)} successful")
    if best: print(f"  Best: AUC={best['macro_roc_auc']:.6f} | {best['description']}")
    return all_results, best
 
 
# ═══════════════════════════════════════════════════════════════════════════
# INSIGHTS & NOTEBOOK GENERATION
# ═══════════════════════════════════════════════════════════════════════════
 
def _generate_insights(llm, results, phase, dirs, temperature):
    ok = [r for r in results if r.get("success") and r.get("macro_roc_auc")]
    if not ok:
        (dirs["logs"] / f"{phase}_final_result_insights.txt").write_text(
            f"No successful experiments in {phase} phase.\n", encoding="utf-8")
        return
    ok.sort(key=lambda r: r["macro_roc_auc"], reverse=True)
    lines = []
    for i, r in enumerate(ok):
        l = f"{i+1}. AUC={r['macro_roc_auc']:.6f} | {r['description']}"
        if r.get("dimension"): l += f" [{r['dimension']}]"
        if r.get("search_type"): l += f" [{r['search_type']}]"
        lines.append(l)
    prompt = (
        f"Results from {phase} search for bird species audio classification (BirdCLEF 2026).\n"
        f"234 species, mel spectrograms, metric=macro_roc_auc, trained on 300 samples 3 epochs.\n\n"
        f"Results (best to worst):\n" + "\n".join(lines) + "\n\n"
        "Write a concise analysis (~half page): biggest impact params, best values, "
        "surprises, recommendations for the final model. Plain text, no code."
    )
    print(f"\n  Generating {phase} insights...")
    resp = llm.generate_from_messages(
        messages=[{"role":"system","content":"You are an ML research analyst."},
                  {"role":"user","content":prompt}],
        temperature=temperature)
    out = dirs["logs"] / f"{phase}_final_result_insights.txt"
    out.write_text(resp, encoding="utf-8")
    print(f"  Saved to {out}")
 
 
def _generate_kaggle_notebook(params, output_path):
    nm, nf = params.get("n_mels", 64), params.get("n_frames", 128)
    nb = {
        "nbformat": 4, "nbformat_minor": 4,
        "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}},
        "cells": [
            {"cell_type": "markdown", "metadata": {}, "source": [
                "# BirdCLEF+ 2026 — Inference Notebook\n",
                "Auto-generated by structured search agent.\n",
                f"Config: {describe_params(params)}\n"]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
                "import os, numpy as np, pandas as pd, librosa, tensorflow as tf\n",
                "from pathlib import Path\n",
                f"\nSR = 32000\nCLIP_SECONDS = 5.0\nN_MELS = {nm}\nN_FRAMES = {nf}\n",
                "N_FFT = 1024\nHOP_LENGTH = 512\n",
                "\nCOMP_DIR = '/kaggle/input/birdclef-2026'\n",
                "MODEL_DIR = '/kaggle/input/birdclef-model'\n"]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
                "model = tf.keras.models.load_model(os.path.join(MODEL_DIR, 'model.keras'))\n",
                "sample_sub = pd.read_csv(os.path.join(COMP_DIR, 'sample_submission.csv'))\n",
                "species_cols = [c for c in sample_sub.columns if c != 'row_id']\n",
                "print(f'Model loaded. Species: {len(species_cols)}')\n"]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
                "test_dir = Path(COMP_DIR) / 'test_soundscapes'\n",
                "test_files = sorted(test_dir.glob('*.ogg')) if test_dir.exists() else []\n",
                "print(f'Test soundscapes: {len(test_files)}')\n",
                "\nall_rows = []\nseg_samples = int(SR * CLIP_SECONDS)\n",
                "\nfor fpath in test_files:\n",
                "    name = fpath.stem\n",
                "    y_full, _ = librosa.load(str(fpath), sr=SR, mono=True)\n",
                "    for start in range(0, len(y_full), seg_samples):\n",
                "        seg = y_full[start:start+seg_samples]\n",
                "        if len(seg) < seg_samples:\n",
                "            seg = np.pad(seg, (0, seg_samples - len(seg)))\n",
                "        end_sec = (start // seg_samples + 1) * CLIP_SECONDS\n",
                "        mel = librosa.feature.melspectrogram(\n",
                "            y=seg, sr=SR, n_mels=N_MELS, n_fft=N_FFT, hop_length=HOP_LENGTH, power=2.0)\n",
                "        mel_db = librosa.power_to_db(mel, ref=np.max)\n",
                "        mel_r = tf.image.resize(mel_db[..., np.newaxis], (N_MELS, N_FRAMES)).numpy().astype(np.float32)\n",
                "        preds = model.predict(mel_r[np.newaxis, ...], verbose=0)[0]\n",
                "        row = {'row_id': f'{name}_{end_sec}'}\n",
                "        for col, p in zip(species_cols, preds):\n",
                "            row[col] = float(p)\n",
                "        all_rows.append(row)\n",
                "\nprint(f'Prediction rows: {len(all_rows)}')\n"]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
                "sub = pd.DataFrame(all_rows) if all_rows else sample_sub.copy()\n",
                "sub = sample_sub[['row_id']].merge(sub, on='row_id', how='left')\n",
                "sub[species_cols] = sub[species_cols].fillna(0.0).clip(0.0, 1.0)\n",
                "sub.to_csv('/kaggle/working/submission.csv', index=False)\n",
                "print(f'Submission saved: {sub.shape}')\n"]},
        ]
    }
    output_path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
 
 
# ═══════════════════════════════════════════════════════════════════════════
# PHASE 3: FINAL TRAINING
# ═══════════════════════════════════════════════════════════════════════════
 
def _final_execution_timeout_seconds(config: dict) -> int | None:
    """Timeout for Phase 3 subprocess. None = no limit (run until finish)."""
    ex = config.get("execution", {})
    if "final_timeout_seconds" not in ex:
        return None
    return ex["final_timeout_seconds"]


def _run_final_training(best_params, executor, evaluator, llm, temperature, project_root, dirs, search_cfg):
    print("\n" + "=" * 60)
    print("  PHASE 3: FINAL TRAINING")
    print("=" * 60)
 
    sub_dir = project_root / "submission"
    sub_dir.mkdir(parents=True, exist_ok=True)
    model_path = str(sub_dir / "model.keras")
 
    fp = dict(best_params)
    fp["max_samples"] = search_cfg["final"].get("max_samples")
    fp["epochs"] = search_cfg["final"]["epochs"]
 
    slot_code = generate_slot_code(fp)
    script = assemble_script(slot_code, is_final=True, model_save_path=model_path)
    script = _append_eval_wrapper(script, "final", dirs["eval"])
 
    script_path = dirs["logs"] / "final_run.py"
    script_path.write_text(script, encoding="utf-8")
    (sub_dir / "best_model_code.py").write_text(slot_code, encoding="utf-8")
 
    print(f"  Config: {describe_params(best_params)}")
    print(f"  Epochs: {fp['epochs']}, Samples: {'ALL' if fp['max_samples'] is None else fp['max_samples']}")
 
    t0 = time.time()
    result = executor.run_file(script_path)
    dt = time.time() - t0
 
    if result.success:
        print(f"  ✓ SUCCESS ({dt:.1f}s)")
        yt, yp = dirs["eval"] / "y_true_final.npy", dirs["eval"] / "y_pred_final.npy"
        if yt.exists() and yp.exists():
            ev = evaluator.evaluate_from_files(yt, yp)
            if ev.metrics.get("status") == "success":
                print(f"  macro_roc_auc = {ev.metrics['macro_roc_auc']:.6f}")
                print(f"  scored_species = {ev.metrics['num_scored_columns']}")
                print(f"  samples = {ev.metrics['num_samples']}")
        if Path(model_path).exists():
            print(f"  Model: {model_path} ({Path(model_path).stat().st_size/1024/1024:.1f} MB)")
        nb_path = sub_dir / "kaggle_inference.ipynb"
        _generate_kaggle_notebook(best_params, nb_path)
        print(f"  Kaggle notebook: {nb_path}")
        _save_json(best_params, sub_dir / "best_params.json")
        print(f"\n  submission/ contents:")
        for f in sorted(sub_dir.iterdir()):
            print(f"    {f.name} ({f.stat().st_size/1024:.1f} KB)")
    else:
        print(f"  ✗ FAILED ({dt:.1f}s) — attempting LLM fix...")
        slot_code, metrics, _, att = run_experiment_until_success(
            slot_code, "final_retry", dirs["logs"], dirs["eval"], executor, evaluator, llm, temperature)
        if metrics and metrics.get("status") == "success":
            print(f"  Fixed after {att} attempts. AUC={metrics['macro_roc_auc']:.6f}")
            (sub_dir / "best_model_code.py").write_text(slot_code, encoding="utf-8")
            _generate_kaggle_notebook(best_params, sub_dir / "kaggle_inference.ipynb")
 
 
# ═══════════════════════════════════════════════════════════════════════════
# PHASE 3 ONLY (standalone rerun)
# ═══════════════════════════════════════════════════════════════════════════


def _load_best_params_for_final(project_root: Path, best_params_path: Path | None) -> dict:
    """Resolve hyperparameters for final training from explicit file or saved search outputs."""
    if best_params_path is not None and best_params_path.exists():
        data = json.loads(best_params_path.read_text(encoding="utf-8"))
        if isinstance(data, dict) and "params" in data and isinstance(data["params"], dict):
            return {**DEFAULT_PARAMS, **data["params"]}
        if isinstance(data, dict):
            return {**DEFAULT_PARAMS, **data}

    comp = project_root / "logs" / "search_comparison.json"
    if comp.exists():
        data = json.loads(comp.read_text(encoding="utf-8"))
        fp = data.get("final_params")
        if isinstance(fp, dict):
            return {**DEFAULT_PARAMS, **fp}

    bp = project_root / "submission" / "best_params.json"
    if bp.exists():
        data = json.loads(bp.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return {**DEFAULT_PARAMS, **data}

    return dict(DEFAULT_PARAMS)


def run_phase3_final_only(
    project_root: Path | None = None,
    config_path: Path | None = None,
    *,
    best_params_path: Path | None = None,
) -> None:
    """
    Run Phase 3 (final training + eval artifacts + notebook) only.

    Loads best hyperparameters from, in order:
    1) ``best_params_path`` if provided and exists
    2) ``logs/search_comparison.json`` → ``final_params``
    3) ``submission/best_params.json``
    4) ``DEFAULT_PARAMS``

    Uses ``execution.final_timeout_seconds`` from config (``null`` = no subprocess timeout).
    """
    root = project_root or Path(__file__).resolve().parents[1]
    cfg_path = config_path or (root / "configs" / "agent_config.json")
    config = json.loads(cfg_path.read_text(encoding="utf-8"))

    logs = root / "logs"
    dirs = {
        "logs": logs,
        "eval": logs / "eval_artifacts",
        "linear_codes": logs / "linear_codes",
        "random_codes": logs / "random_codes",
        "baseline_codes": logs / "baseline_codes",
    }
    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True)

    sc = config.get("search", {})
    sc.setdefault("final", {"max_samples": None, "epochs": 20})

    best_params = _load_best_params_for_final(root, best_params_path)

    py_exe = config["execution"]["python_executable"]
    executor_final = CodeExecutor(
        python_executable=py_exe,
        timeout_seconds=_final_execution_timeout_seconds(config),
    )
    evaluator = Evaluator(row_id_column_name="row_id")
    llm = LLMClient(provider=config["llm"]["provider"], model=config["llm"]["model"])
    temp = config["llm"].get("temperature", 0.2)

    print("=" * 60)
    print("  PHASE 3 ONLY (final training)")
    print("=" * 60)
    print(f"  Params: {describe_params(best_params)}")
    ft = _final_execution_timeout_seconds(config)
    print(f"  Subprocess timeout: {'unlimited' if ft is None else f'{ft}s'}")
    print("=" * 60)

    _run_final_training(best_params, executor_final, evaluator, llm, temp, root, dirs, sc)


# ═══════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════
 
def agent_loop(config):
    root = Path(__file__).resolve().parents[1]
    logs = root / "logs"
    dirs = {k: logs / v for k, v in {
        "logs": "", "eval": "eval_artifacts", "linear_codes": "linear_codes",
        "random_codes": "random_codes", "baseline_codes": "baseline_codes"}.items()}
    dirs["logs"] = logs
    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True)
 
    sc = config.get("search", {})
    sc.setdefault("cheap", {"max_samples": 300, "epochs": 3})
    sc.setdefault("medium", {"max_samples": 2000, "epochs": 10})
    sc.setdefault("final", {"max_samples": None, "epochs": 20})
    sc.setdefault("linear_budget", 75)
    sc.setdefault("random_budget", 50)
    sc.setdefault("random_seed", config.get("random_seed", 42))
 
    llm = LLMClient(provider=config["llm"]["provider"], model=config["llm"]["model"])
    py_exe = config["execution"]["python_executable"]
    search_timeout = config["execution"].get("timeout_seconds", 1800)
    executor_search = CodeExecutor(python_executable=py_exe, timeout_seconds=search_timeout)
    executor_final = CodeExecutor(
        python_executable=py_exe,
        timeout_seconds=_final_execution_timeout_seconds(config),
    )
    evaluator = Evaluator(row_id_column_name="row_id")
    temp = config["llm"].get("temperature", 0.2)
 
    print("=" * 60)
    print("  BirdCLEF Structured Search Agent")
    print("=" * 60)
    print(f"  LLM:     {config['llm']['model']}")
    print(f"  Linear:  {sc['linear_budget']} iters | Random: {sc['random_budget']} iters")
    print(f"  Cheap:   {sc['cheap']['max_samples']} samples, {sc['cheap']['epochs']} epochs")
    print(f"  Final:   {'ALL' if sc['final']['max_samples'] is None else sc['final']['max_samples']} samples, {sc['final']['epochs']} epochs")
    ft = _final_execution_timeout_seconds(config)
    print(f"  Final subprocess timeout: {'unlimited' if ft is None else f'{ft}s'}")
    print("=" * 60)
 
    t0 = time.time()
 
    baseline_slot, _ = _run_baseline(executor_search, evaluator, llm, temp, dirs, sc)
 
    lin_results, lin_best = _run_linear_search(baseline_slot, executor_search, evaluator, llm, temp, dirs, sc)
    _generate_insights(llm, lin_results, "linear", dirs, temp)
    lin_ok = [r for r in lin_results if r.get("success") and r.get("macro_roc_auc")]
    best_lin_auc = max((r["macro_roc_auc"] for r in lin_ok), default=0.0)
 
    rnd_results, best_rnd = _run_random_search(baseline_slot, executor_search, evaluator, llm, temp, dirs, sc)
    _generate_insights(llm, rnd_results, "random", dirs, temp)
    best_rnd_auc = best_rnd["macro_roc_auc"] if best_rnd else 0.0
 
    print("\n" + "=" * 60)
    print("  COMPARISON: LINEAR vs RANDOM")
    print("=" * 60)
    print(f"  Linear: AUC={best_lin_auc:.6f} | {describe_params(lin_best)}")
    print(f"  Random: AUC={_fmt_score(best_rnd_auc)} | {best_rnd['description'] if best_rnd else 'N/A'}")
 
    if best_rnd_auc > best_lin_auc and best_rnd:
        best_params, winner = best_rnd["params"], "random"
    else:
        best_params, winner = lin_best, "linear"
    print(f"\n  ★ WINNER: {winner} (AUC={max(best_lin_auc, best_rnd_auc):.6f})")
 
    _save_json({"best_linear_auc": best_lin_auc, "best_linear_params": lin_best,
                "best_random_auc": best_rnd_auc,
                "best_random_params": best_rnd["params"] if best_rnd else None,
                "winner": winner, "final_params": best_params},
               logs / "search_comparison.json")
 
    total = len(lin_results) + len(rnd_results) + 1
    print(f"\n  Total: {total} experiments in {(time.time()-t0)/60:.1f} min")
 
    if best_lin_auc > 0 or best_rnd_auc > 0:
        _run_final_training(best_params, executor_final, evaluator, llm, temp, root, dirs, sc)
    else:
        print("\n  No successful experiments — skipping final training.")
 
 
def main():
    root = Path(__file__).resolve().parents[1]
    config = json.loads((root / "configs" / "agent_config.json").read_text())
    agent_loop(config)
 
if __name__ == "__main__":
    main()