"""
Autonomous BirdCLEF Research Agent (Slot Mode)
===============================================

Architecture:
  - Fixed harness: loads data, builds mel features, trains, evaluates, writes submission
  - LLM slot:      writes only build_model() + get_training_config() (+ optional build_features())
  - Agent loop:    run -> evaluate -> feed results back -> LLM proposes improvement -> repeat
  - Final run:     retrain best architecture on ALL data, save model + submission + Kaggle notebook
"""

from __future__ import annotations

import json
import re
import ast
import time
from pathlib import Path
from datetime import datetime

if __package__:
    from .code_executor import CodeExecutor
    from .evaluator import Evaluator
    from .llm_client import LLMClient
else:
    from code_executor import CodeExecutor
    from evaluator import Evaluator
    from llm_client import LLMClient


def load_config(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Fixed harness prefix (shared by iteration runs and final run)
# ---------------------------------------------------------------------------

HARNESS_PREFIX = '''
"""Auto-generated by agent: fixed harness + LLM slots."""
from __future__ import annotations
import os, sys, json
from pathlib import Path
import librosa, numpy as np, tensorflow as tf, matplotlib.pyplot as plt

_PROJECT_ROOT = str(Path(__file__).resolve().parents[1])
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)
os.chdir(_PROJECT_ROOT)
os.environ.setdefault("BIRDCLEF_DATA_DIR", str(Path(_PROJECT_ROOT) / "data"))

from src.data_io import (
    load_core_tables, resolve_birdclef_paths,
    species_columns_from_sample_submission, validate_required_files,
)

def _default_load_mel(audio_path, sample_rate, clip_seconds, n_mels, n_frames):
    target_len = int(sample_rate * clip_seconds)
    wav, _ = librosa.load(audio_path, sr=sample_rate, mono=True, duration=clip_seconds)
    if len(wav) < target_len:
        wav = np.pad(wav, (0, target_len - len(wav)))
    else:
        wav = wav[:target_len]
    mel = librosa.feature.melspectrogram(
        y=wav, sr=sample_rate, n_mels=n_mels, n_fft=1024, hop_length=512, power=2.0,
    )
    mel_db = librosa.power_to_db(mel, ref=np.max)
    mel_resized = tf.image.resize(mel_db[..., np.newaxis], (n_mels, n_frames)).numpy()
    return mel_resized.astype(np.float32)
'''.lstrip()


def _make_harness_suffix(*, is_final: bool = False, model_save_path: str = "") -> str:
    if is_final:
        max_line = '    max_samples = None  # FINAL RUN: use ALL data'
        save_block = (
            f'\n    _mp = Path({repr(str(model_save_path))})\n'
            '    _mp.parent.mkdir(parents=True, exist_ok=True)\n'
            '    model.save(_mp)\n'
            '    print(f"MODEL_SAVED: {_mp}")\n'
        )
    else:
        max_line = '    max_samples = cfg.get("max_samples", 500)'
        save_block = ''

    return f'''

def main():
    global model, X_train, y_train
    tf.keras.utils.set_random_seed(42)
    cfg = get_training_config()
{max_line}
    sample_rate   = cfg.get("sample_rate", 32000)
    clip_seconds  = cfg.get("clip_seconds", 5.0)
    n_mels        = cfg.get("n_mels", 64)
    n_frames      = cfg.get("n_frames", 128)
    epochs        = cfg.get("epochs", 5)
    batch_size    = cfg.get("batch_size", 32)
    learning_rate = cfg.get("learning_rate", 1e-3)

    paths = resolve_birdclef_paths()
    missing = validate_required_files(paths)
    if missing:
        raise FileNotFoundError(f"Missing: {{missing}}")
    tables = load_core_tables(paths)
    train_df = tables["train"]
    sample_sub = tables["sample_submission"]
    species_cols = species_columns_from_sample_submission(sample_sub)
    num_species = len(species_cols)
    sp2i = {{s: i for i, s in enumerate(species_cols)}}
    lcol = "primary_label" if "primary_label" in train_df.columns else "species_code"
    fcol = "filename" if "filename" in train_df.columns else "filepath"

    mel_fn = build_features if "build_features" in dir() and callable(build_features) else _default_load_mel

    X_items, y_items = [], []
    total = len(train_df)
    for i, row in enumerate(train_df.itertuples(index=False)):
        label = getattr(row, lcol)
        rel = getattr(row, fcol)
        if label not in sp2i:
            continue
        ap = paths.train_audio_dir / str(rel)
        if not ap.exists():
            continue
        try:
            mel = mel_fn(ap, sample_rate, clip_seconds, n_mels, n_frames)
        except Exception:
            continue
        yv = np.zeros(num_species, dtype=np.float32)
        yv[sp2i[label]] = 1.0
        X_items.append(mel)
        y_items.append(yv)
        if max_samples and len(X_items) >= max_samples:
            break
        if len(X_items) % 500 == 0:
            print(f"  Loaded {{len(X_items)}} samples (row {{i+1}}/{{total}})...")

    if not X_items:
        raise RuntimeError("No samples loaded.")
    X_train = np.stack(X_items, dtype=np.float32)
    y_train = np.stack(y_items, dtype=np.float32)
    print(f"DATA: X_train={{X_train.shape}}, y_train={{y_train.shape}}")

    model = build_model(X_train.shape[1:], num_species)
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate), loss="binary_crossentropy")
    model.summary()
    history = model.fit(X_train, y_train, epochs=epochs, batch_size=min(batch_size, len(X_train)), verbose=1)
    print(f"TRAIN_LOSS: {{history.history['loss'][-1]:.6f}}")
{save_block}
    y_pred = model.predict(X_train, verbose=0).astype(np.float32)
    mean_pred = y_pred.mean(axis=0)
    sub_df = sample_sub.copy()
    for i, col in enumerate(species_cols):
        sub_df[col] = float(mean_pred[i])
    sub_path = Path("submission/submission_generated.csv")
    sub_path.parent.mkdir(parents=True, exist_ok=True)
    sub_df.to_csv(sub_path, index=False)
    print(f"SUBMISSION: {{sub_path}}")

if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Default slot code
# ---------------------------------------------------------------------------

DEFAULT_SLOT_CODE = '''EXPERIMENT_META = {
    "model_type": "cnn",
    "architecture": "3x Conv2D + GAP + Dropout",
    "change": "baseline",
    "key_params": {"lr": 1e-3, "batch_size": 32, "epochs": 5},
}


def get_training_config():
    return {
        "max_samples": 500,
        "sample_rate": 32000,
        "clip_seconds": 5.0,
        "n_mels": 64,
        "n_frames": 128,
        "epochs": 5,
        "batch_size": 32,
        "learning_rate": 1e-3,
    }


def build_model(input_shape, num_classes):
    import tensorflow as tf
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=input_shape),
        tf.keras.layers.Conv2D(16, (3, 3), activation="relu", padding="same"),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(64, (3, 3), activation="relu", padding="same"),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(num_classes, activation="sigmoid"),
    ])
    model.compile(optimizer="adam", loss="binary_crossentropy")
    return model
'''


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "You are an ML research assistant. You write Python functions to define "
    "neural network architectures for bird species audio classification.\n\n"
    "RULES:\n"
    "- Return ONLY a ```python``` code block, nothing else\n"
    "- Define exactly: get_training_config(), build_model(input_shape, num_classes), and EXPERIMENT_META\n"
    "- Optionally define: build_features(audio_path, sample_rate, clip_seconds, n_mels, n_frames)\n"
    "- Do NOT define main(), do NOT load data, do NOT write submission logic\n"
    "- build_model must return a COMPILED Keras model\n"
    "- Last layer must be Dense(num_classes, activation='sigmoid')\n"
    "- Loss must be 'binary_crossentropy'\n"
    "- input_shape is passed as a parameter. ALWAYS use it as-is. NEVER hardcode any input shape.\n"
    "- Default input_shape is (64, 128, 1): 64 mel bins, 128 time frames, 1 channel\n"
    "- num_classes is 234 (one per bird species)\n\n"
    "CNN EXAMPLE (correct pattern):\n"
    "    def build_model(input_shape, num_classes):\n"
    "        import tensorflow as tf\n"
    "        inputs = tf.keras.Input(shape=input_shape)\n"
    "        x = tf.keras.layers.Conv2D(32, 3, activation='relu', padding='same')(inputs)\n"
    "        x = tf.keras.layers.GlobalAveragePooling2D()(x)\n"
    "        x = tf.keras.layers.Dropout(0.3)(x)\n"
    "        out = tf.keras.layers.Dense(num_classes, activation='sigmoid')(x)\n"
    "        model = tf.keras.Model(inputs, out)\n"
    "        model.compile(optimizer='adam', loss='binary_crossentropy')\n"
    "        return model\n\n"
    "TRANSFER LEARNING:\n"
    "- Only switch to pretrained when explicitly told CNN results are stagnating\n"
    "- For the first pretrained run: freeze the backbone (base.trainable = False)\n"
    "- Only unfreeze if a frozen pretrained run already improved results\n"
    "- You MUST resize and repeat channels INSIDE build_model using Keras layers\n"
    "- PRETRAINED EXAMPLE (complete, use exactly this pattern):\n"
    "    def build_model(input_shape, num_classes):\n"
    "        import tensorflow as tf\n"
    "        inputs = tf.keras.Input(shape=input_shape)\n"
    "        x = tf.keras.layers.Resizing(96, 96)(inputs)\n"
    "        x = tf.keras.layers.Lambda(lambda t: tf.repeat(t, 3, axis=-1))(x)\n"
    "        base = tf.keras.applications.MobileNetV2(input_shape=(96,96,3), include_top=False, weights='imagenet')\n"
    "        base.trainable = False\n"
    "        x = base(x)\n"
    "        x = tf.keras.layers.GlobalAveragePooling2D()(x)\n"
    "        out = tf.keras.layers.Dense(num_classes, activation='sigmoid')(x)\n"
    "        model = tf.keras.Model(inputs=inputs, outputs=out)\n"
    "        model.compile(optimizer='adam', loss='binary_crossentropy')\n"
    "        return model\n\n"
    "EXPERIMENT_META must be a dict with these keys:\n"
    "    model_type: 'cnn' | 'pretrained'\n"
    "    architecture: short description, e.g. '3x Conv2D + GAP' or 'MobileNetV2 frozen'\n"
    "    change: what you changed vs the previous run, or 'baseline' for the first run\n"
    "    key_params: dict with lr, batch_size, epochs, and any other relevant params\n"
)

SEED_PROMPT = (
    "Write get_training_config() and build_model() for BirdCLEF 2026.\n\n"
    "Task: multi-label bird species classification from mel spectrograms.\n"
    "Input: mel spectrogram of shape (n_mels, n_frames, 1), default (64, 128, 1).\n"
    "Output: 234 species probabilities (sigmoid).\n"
    "Loss: binary_crossentropy.\n\n"
    "Data info:\n"
    "- ~24,000 training audio clips (.ogg) in data/train_audio/\n"
    "- train.csv columns: primary_label, filename, secondary_labels, latitude, longitude, "
    "scientific_name, common_name, etc.\n"
    "- 234 target species defined by sample_submission.csv\n"
    "- Audio is 5-second clips converted to mel spectrograms\n\n"
    "Start with a simple CNN baseline (Conv2D blocks + GlobalAveragePooling).\n\n"
    "Here is the starting code to modify:\n"
    f"```python\n{DEFAULT_SLOT_CODE}```"
)


def _build_feedback_prompt(*, stdout, stderr, is_error, metrics, current_code, cnn_stagnating=False):
    if is_error:
        return (
            "The last run FAILED with this error:\n"
            f"```\n{_truncate(stderr, 3000)}\n```\n\n"
            "Fix the bug. Return the corrected get_training_config() and build_model().\n"
            f"Current code:\n```python\n{current_code}\n```"
        )
    metrics_str = ""
    if metrics:
        metrics_str = (
            f"macro_roc_auc = {metrics.get('macro_roc_auc', 'N/A')}\n"
            f"scored_species = {metrics.get('num_scored_columns', '?')}\n"
            f"training_samples = {metrics.get('num_samples', '?')}\n"
        )
    if cnn_stagnating:
        improvement_hint = (
            "CNN results have been flat for the last 3 runs — no meaningful improvement.\n"
            "Switch to transfer learning: use MobileNetV2 as a frozen pretrained backbone.\n"
            "Follow the pretrained example in the system prompt exactly.\n"
            "Set model_type='pretrained' and architecture='MobileNetV2 frozen' in EXPERIMENT_META.\n"
        )
    else:
        improvement_hint = (
            "Propose ONE specific improvement to increase macro_roc_auc. Options:\n"
            "- More/fewer Conv2D layers or filters\n"
            "- Add BatchNormalization\n"
            "- Change dropout, learning rate, epochs, batch size\n"
            "- Increase max_samples\n"
            "- Change n_mels, n_frames\n"
            "- Add data augmentation in build_features()\n"
        )
    return (
        "The last experiment completed successfully.\n\n"
        f"Results:\n{metrics_str}\n"
        f"Training output:\n{_truncate(stdout, 2000)}\n\n"
        + improvement_hint
        + f"\nReturn the complete updated code.\nCurrent code:\n```python\n{current_code}\n```"
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _truncate(text, max_chars=4000):
    return text if len(text) <= max_chars else text[:max_chars] + "\n...[truncated]..."


def extract_python_code(response):
    if not response or not response.strip():
        return ""
    blocks = re.findall(r"```python\s*(.*?)```", response, re.IGNORECASE | re.DOTALL)
    if blocks:
        return blocks[0].strip()
    blocks = re.findall(r"```(?:\w+)?\s*(.*?)```", response, re.DOTALL)
    if blocks:
        return blocks[0].strip()
    return ""


def validate_slot_code(code):
    issues = []
    try:
        ast.parse(code)
    except SyntaxError as e:
        return [f"SyntaxError: {e}"]
    if not re.search(r"def\s+build_model\s*\(", code):
        issues.append("Missing: def build_model(input_shape, num_classes)")
    if not re.search(r"def\s+get_training_config\s*\(", code):
        issues.append("Missing: def get_training_config()")
    if not re.search(r"EXPERIMENT_META\s*=\s*\{", code):
        issues.append("Missing: EXPERIMENT_META = {...}")
    if re.search(r"def\s+main\s*\(", code):
        issues.append("Do NOT define main()")
    return issues


def extract_experiment_meta(slot_code: str) -> dict:
    """Safely executes slot code in a sandbox and extracts EXPERIMENT_META."""
    ns = {}
    try:
        exec(slot_code, ns)
        meta = ns.get("EXPERIMENT_META", {})
        if isinstance(meta, dict):
            return meta
    except Exception:
        pass
    return {}


def assemble_script(slot_code, *, is_final=False, model_save_path=""):
    suffix = _make_harness_suffix(is_final=is_final, model_save_path=model_save_path)
    return f"{HARNESS_PREFIX}\n# ── LLM-generated slots ──\n\n{slot_code.strip()}\n\n{suffix}"


def _append_eval_wrapper(script, iteration, eval_dir):
    yt = eval_dir / f"y_true_iter_{iteration}.npy"
    yp = eval_dir / f"y_pred_iter_{iteration}.npy"
    return script + f'''

import numpy as _np
_yt = _np.asarray(y_train)
_yp = _np.asarray(model.predict(X_train, verbose=0))
if _yt.shape != _yp.shape:
    raise RuntimeError(f"Shape mismatch: y_train={{_yt.shape}} vs y_pred={{_yp.shape}}")
_np.save({repr(str(yt))}, _yt)
_np.save({repr(str(yp))}, _yp)
print("EVAL_ARTIFACTS_SAVED y_true=" + {repr(str(yt))} + " y_pred=" + {repr(str(yp))})
'''


def _trim_and_append(messages, role, content):
    messages.append({"role": role, "content": content})
    if len(messages) > 6:
        messages = messages[:2] + messages[-4:]
    return messages


def _save_metrics(history, path):
    path.write_text(json.dumps(history, indent=2), encoding="utf-8")


# ---------------------------------------------------------------------------
# Kaggle inference notebook generator
# ---------------------------------------------------------------------------

def _generate_kaggle_notebook(slot_code, output_path):
    ns = {}
    try:
        exec(slot_code, ns)
        cfg = ns.get("get_training_config", lambda: {})()
    except Exception:
        cfg = {}

    sr = cfg.get("sample_rate", 32000)
    cs = cfg.get("clip_seconds", 5.0)
    nm = cfg.get("n_mels", 64)
    nf = cfg.get("n_frames", 128)

    nb = {
        "nbformat": 4, "nbformat_minor": 4,
        "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}},
        "cells": [
            {"cell_type": "markdown", "metadata": {}, "source": [
                "# BirdCLEF+ 2026 — Inference Notebook\n",
                "Auto-generated by the autonomous research agent.\n",
                "Upload model.keras as a Kaggle dataset and reference it below."
            ]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
                "import os, numpy as np, pandas as pd, librosa, tensorflow as tf\n",
                "from pathlib import Path\n",
                "\n",
                f"SR = {sr}\n",
                f"CLIP_SECONDS = {cs}\n",
                f"N_MELS = {nm}\n",
                f"N_FRAMES = {nf}\n",
                "N_FFT = 1024\n",
                "HOP_LENGTH = 512\n",
                "\n",
                "COMP_DIR = '/kaggle/input/birdclef-2026'\n",
                "MODEL_DIR = '/kaggle/input/birdclef-model'  # your uploaded model dataset\n",
            ]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
                "model = tf.keras.models.load_model(os.path.join(MODEL_DIR, 'model.keras'))\n",
                "sample_sub = pd.read_csv(os.path.join(COMP_DIR, 'sample_submission.csv'))\n",
                "species_cols = [c for c in sample_sub.columns if c != 'row_id']\n",
                "print(f'Model loaded. Species: {len(species_cols)}')\n",
            ]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
                "test_dir = Path(COMP_DIR) / 'test_soundscapes'\n",
                "test_files = sorted(test_dir.glob('*.ogg')) if test_dir.exists() else []\n",
                "print(f'Test soundscapes: {len(test_files)}')\n",
                "\n",
                "all_rows = []\n",
                "seg_samples = SR * CLIP_SECONDS\n",
                "\n",
                "for fpath in test_files:\n",
                "    name = fpath.stem\n",
                "    y_full, _ = librosa.load(str(fpath), sr=SR, mono=True)\n",
                "    for start in range(0, len(y_full), seg_samples):\n",
                "        seg = y_full[start:start+seg_samples]\n",
                "        if len(seg) < seg_samples:\n",
                "            seg = np.pad(seg, (0, seg_samples - len(seg)))\n",
                "        end_sec = (start // seg_samples + 1) * CLIP_SECONDS\n",
                "        mel = librosa.feature.melspectrogram(\n",
                "            y=seg, sr=SR, n_mels=N_MELS, n_fft=N_FFT, hop_length=HOP_LENGTH, power=2.0)\n",
                "        mel_db = librosa.power_to_db(mel, ref=np.max)\n",
                "        mel_r = tf.image.resize(mel_db[..., np.newaxis], (N_MELS, N_FRAMES)).numpy().astype(np.float32)\n",
                "        preds = model.predict(mel_r[np.newaxis, ...], verbose=0)[0]\n",
                "        row = {'row_id': f'{name}_{end_sec}'}\n",
                "        for col, p in zip(species_cols, preds):\n",
                "            row[col] = float(p)\n",
                "        all_rows.append(row)\n",
                "\n",
                "print(f'Prediction rows: {len(all_rows)}')\n",
            ]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
                "sub = pd.DataFrame(all_rows) if all_rows else sample_sub.copy()\n",
                "sub = sample_sub[['row_id']].merge(sub, on='row_id', how='left')\n",
                "sub[species_cols] = sub[species_cols].fillna(0.0).clip(0.0, 1.0)\n",
                "sub.to_csv('/kaggle/working/submission.csv', index=False)\n",
                "print(f'Submission saved: {sub.shape}')\n",
            ]},
        ]
    }
    output_path.write_text(json.dumps(nb, indent=1), encoding="utf-8")


# ---------------------------------------------------------------------------
# Final run
# ---------------------------------------------------------------------------

def _run_final(*, best_slot_code, executor, evaluator, project_root):
    sub_dir = project_root / "submission"
    sub_dir.mkdir(parents=True, exist_ok=True)
    logs_dir = project_root / "logs"
    eval_dir = logs_dir / "eval_artifacts"
    model_path = str(sub_dir / "model.keras")

    print("\n" + "=" * 60)
    print("  FINAL RUN: Retraining best model on ALL data")
    print("=" * 60)

    script = assemble_script(best_slot_code, is_final=True, model_save_path=model_path)
    script = _append_eval_wrapper(script, 999, eval_dir)
    script_path = logs_dir / "final_run.py"
    script_path.write_text(script, encoding="utf-8")

    t0 = time.time()
    result = executor.run_file(script_path)
    dt = time.time() - t0

    if result.success:
        print(f"  SUCCESS ({dt:.1f}s)")
        yt = eval_dir / "y_true_iter_999.npy"
        yp = eval_dir / "y_pred_iter_999.npy"
        if yt.exists() and yp.exists():
            ev = evaluator.evaluate_from_files(yt, yp)
            if ev.metrics.get("status") == "success":
                print(f"  macro_roc_auc = {ev.metrics['macro_roc_auc']:.6f}")
                print(f"  scored_species = {ev.metrics['num_scored_columns']}")
                print(f"  samples = {ev.metrics['num_samples']}")

        if Path(model_path).exists():
            mb = Path(model_path).stat().st_size / (1024*1024)
            print(f"  Model: {model_path} ({mb:.1f} MB)")

        nb_path = sub_dir / "kaggle_inference.ipynb"
        _generate_kaggle_notebook(best_slot_code, nb_path)
        print(f"  Kaggle notebook: {nb_path}")

        (sub_dir / "best_model_code.py").write_text(best_slot_code, encoding="utf-8")

        print(f"\n  submission/ contents:")
        for f in sorted(sub_dir.iterdir()):
            print(f"    {f.name} ({f.stat().st_size/1024:.1f} KB)")
    else:
        print(f"  FAILED ({dt:.1f}s)")
        print(f"  {_truncate(result.stderr, 2000)}")


# ---------------------------------------------------------------------------
# Agent loop
# ---------------------------------------------------------------------------

def agent_loop(config):
    project_root = Path(__file__).resolve().parents[1]
    logs_dir = project_root / "logs"
    eval_dir = logs_dir / "eval_artifacts"
    logs_dir.mkdir(exist_ok=True)
    eval_dir.mkdir(exist_ok=True)

    llm = LLMClient(provider=config["llm"]["provider"], model=config["llm"]["model"])
    executor = CodeExecutor(
        python_executable=config["execution"]["python_executable"],
        timeout_seconds=config["execution"]["timeout_seconds"],
    )
    evaluator = Evaluator(row_id_column_name="row_id")

    max_iters = config.get("max_iterations", 10)
    temp = config["llm"].get("temperature", 0.2)
    current_slot = DEFAULT_SLOT_CODE
    best_slot = DEFAULT_SLOT_CODE
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": SEED_PROMPT},
    ]
    metrics_history = []
    best_auc = 0.0
    consec_fail = 0
    max_fail = config.get("max_failures_before_stop", 5)

    print("=" * 60)
    print("  BirdCLEF Autonomous Research Agent")
    print("=" * 60)
    print(f"  Model:      {config['llm']['model']}")
    print(f"  Iterations: {max_iters}")
    print(f"  Timeout:    {config['execution']['timeout_seconds']}s")
    print("=" * 60)

    for it in range(1, max_iters + 1):
        print(f"\n{'─'*50}\n  ITERATION {it}/{max_iters}\n{'─'*50}")

        # 1. Query LLM
        t0 = time.time()
        print("Querying LLM...")
        resp = llm.generate_from_messages(messages=messages, temperature=temp)
        print(f"LLM responded in {time.time()-t0:.1f}s")

        # 2. Extract & validate
        slot = extract_python_code(resp)
        if not slot:
            print("ERROR: No code in response")
            messages = _trim_and_append(messages, "assistant", resp)
            messages = _trim_and_append(messages, "user",
                "No ```python``` block found. Return ONLY code with get_training_config() and build_model().")
            consec_fail += 1
            metrics_history.append({"iteration": it, "status": "no_code"})
            if consec_fail >= max_fail: break
            continue

        issues = validate_slot_code(slot)
        if issues:
            print(f"Validation: {issues}")
            messages = _trim_and_append(messages, "assistant", resp)
            messages = _trim_and_append(messages, "user",
                f"Errors: {'; '.join(issues)}. Fix and return corrected code.")
            consec_fail += 1
            metrics_history.append({"iteration": it, "status": "validation_failed"})
            if consec_fail >= max_fail: break
            continue

        current_slot = slot
        exp_meta = extract_experiment_meta(slot)

        # 3. Assemble & execute
        full = assemble_script(slot)
        full = _append_eval_wrapper(full, it, eval_dir)
        sp = logs_dir / f"iteration_{it}.py"
        sp.write_text(full, encoding="utf-8")
        (logs_dir / f"slots_{it}.py").write_text(slot, encoding="utf-8")

        print(f"Executing {sp.name}...")
        if exp_meta:
            print(f"  [{exp_meta.get('model_type', '?')}] {exp_meta.get('architecture', '')} — {exp_meta.get('change', '')}")
        t0 = time.time()
        result = executor.run_file(sp)
        dt = time.time() - t0
        print(f"{'SUCCESS' if result.success else 'FAILED'} ({dt:.1f}s)")

        # 4. Evaluate
        em = None
        if result.success:
            consec_fail = 0
            yt = eval_dir / f"y_true_iter_{it}.npy"
            yp = eval_dir / f"y_pred_iter_{it}.npy"
            if yt.exists() and yp.exists():
                try:
                    ev = evaluator.evaluate_from_files(yt, yp)
                    em = ev.metrics
                except Exception as eval_err:
                    print(f"  Evaluation error (skipping): {eval_err}")
                    em = None
                if em.get("status") == "success":
                    auc = em["macro_roc_auc"]
                    print(f"  macro_roc_auc = {auc:.6f} | scored = {em['num_scored_columns']}")
                    if auc > best_auc:
                        best_auc = auc
                        best_slot = slot
                        print(f"  ★ NEW BEST ({best_auc:.6f})")
                        (logs_dir / "best_slots.py").write_text(slot, encoding="utf-8")
            metrics_history.append({
                "iteration": it,
                "status": "success",
                "time": round(dt, 1),
                "macro_roc_auc": em.get("macro_roc_auc") if em else None,
                "experiment_meta": exp_meta,
            })
        else:
            consec_fail += 1
            print(f"  stderr: {_truncate(result.stderr, 200)}")
            metrics_history.append({
                "iteration": it,
                "status": "failed",
                "time": round(dt, 1),
                "experiment_meta": exp_meta,
            })
            if consec_fail >= max_fail: break

        # 5. Feedback — detect CNN stagnation over last 3 successful runs
        recent_aucs = [
            m["macro_roc_auc"] for m in metrics_history[-3:]
            if m["status"] == "success" and m.get("macro_roc_auc") is not None
            and m.get("experiment_meta", {}).get("model_type") == "cnn"
        ]
        cnn_stagnating = (
            len(recent_aucs) >= 3
            and (max(recent_aucs) - min(recent_aucs)) < 0.02
        )
        fb = _build_feedback_prompt(stdout=result.stdout, stderr=result.stderr,
                                     is_error=not result.success, metrics=em,
                                     current_code=current_slot, cnn_stagnating=cnn_stagnating)
        messages = _trim_and_append(messages, "assistant", resp)
        messages = _trim_and_append(messages, "user", fb)
        _save_metrics(metrics_history, logs_dir / "metrics_history.json")

    # ── Summary ──
    print(f"\n{'='*60}")
    ok = sum(1 for m in metrics_history if m["status"] == "success")
    print(f"  EXPLORATION DONE: {ok}/{len(metrics_history)} successful, best AUC = {best_auc:.6f}")
    print(f"{'='*60}")

    (logs_dir / "conversation_history.json").write_text(json.dumps(messages, indent=2), encoding="utf-8")

    # ── Final run on ALL data ──
    if best_auc > 0:
        _run_final(best_slot_code=best_slot, executor=executor, evaluator=evaluator, project_root=project_root)
    else:
        print("\nNo successful iterations — skipping final run.")


def main():
    project_root = Path(__file__).resolve().parents[1]
    config = load_config(project_root / "configs" / "agent_config.json")
    agent_loop(config)

if __name__ == "__main__":
    main()